### PR TITLE
Kenman345 additions oct 19

### PR DESCRIPTION
**Pull request by kenman345**

### CODE REVIEW

**Comment by EchterAgo** [comment]
Do you have some automatic formatter for the files? Could you maybe run it on all yml files to get them all to the same formatting?

**Comment by kenman345** [comment]
I could write something up really quick to loop through and do that. Want me to just add that to this PR?

**Comment by EchterAgo** [comment]
Yea, that would be nice. Right now I'm never sure what formatting I should
use, so I just go with whatever is already used in the file I'm working on.

**Comment by kenman345** [comment]
done

**Comment by EchterAgo** [comment]
Great, thanks!

**Pull request merged**
