### PR TITLE
Fixing the search input lag

### PR DESCRIPTION
**Pull request by kenman345**
Found out this would work a lot better for us, and this is just a copy over and testing of the functionality 2factorauth implemented. In my side by side testing this is a nice and welcomed usability change. @EchterAgo  will you give it a try and check on any bugs too? I did a side by side local running and the current live site and it was definitely less laggy and worked without any real tweaks from what 2fa implemented besides the name of the id we use.

Note: this implements the same changes as 2factorauth#3491

### CODE REVIEW

**Comment by kenman345** [comment]
@Carlgo11 Just wanted to see if you might confirm that I ported that right. Much appreciated if you can chime in.

**Comment by kenman345** [comment]
Travis-CI passed this, its just not appearing for me, but that shouldn't hold up reviewing this for now

**Comment by EchterAgo** [comment]
Great fix! The search has been bugging me for a while now.

**Comment by EchterAgo** [comment]
OK

**Pull request merged**
