### PR TITLE
Remove cryptohabit.com from retail section - the site has gone down

### PR DESCRIPTION
**Pull request by joshmcintyre**
It appears the apparel website cryptohabit.com is down. I'm not entirely sure how long it has been down, but wanted to create a PR in case the site remains offline.

One of those weird domain notices

"Under construction" on the homepage

It's totally possible the site is just down for maintenance, so it may be wise to monitor the site for a few days before pulling the change.

### CODE REVIEW

**Comment by joshmcintyre** [comment]
Just want to follow up; the site is still down as of this posting. Anyone with a twitter want to try and get in touch with the site owner listed in `retail.yml`? It's @theantnest.

**Comment by t0p0lin0** [comment]
Thanks for noticing and creating this issue @joshmcintyre -- I just checked now, and it seems to no longer be a default domain page, so I think @theantnest is working on it:

> This Website is Undergoing Maintenance.
> admin@cryptohabit.com 

Will leave it listed for a bit longer in hopes that it comes back online soon. Will also close this PR to keep the project pruned, but please feel free to open another later if you wish.

**Comment by joshmcintyre** [comment]
Thanks for taking a look, t0p0lin0! Let me know if I can be of assistance for any other parts of the project.

If the site stays down for another few weeks, I'll open another PR.

**Comment by theantnest** [comment]
Sorry guys, this is my site, and yes for now it's down. I've been travelling for work and the site was hacked. Am planning to fix it when I get back home in a few days.

**Comment by t0p0lin0** [comment]
Thanks for the update @theantnest - I will leave it listed.

**Pull request closed without merging**
