### PR TITLE
Add 'Cool Components' to the 'Retail' category

### PR DESCRIPTION
**Pull request by accept-bitcoin-cash**
Requesting to add 'Cool Components' to the 'Electronic components retailer' category. 

Details follow: 
```yml 
- name: Cool Components
  url: https://coolcomponents.co.uk
  img: CoolComponents.png
  bch: true
  btc: true
  othercrypto: false
  twitter: coolcomponents
  facebook: coolcomponents
```

Resources for adding this merchant:
Logo Provided:
ProvidedLogoURL
Twitter Profile Image (48x48):
TwitterProfileImageURL
Facebook Profile Image:
FacebookProfileImageURL
[Link to Cool Components](https://coolcomponents.co.uk)
Check their Twitter Page: [twitter.com/coolcomponents](https://twitter.com/coolcomponents)
Check their Facebook Page: [fb.com/coolcomponents](https://fb.com/coolcomponents)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/coolcomponents.co.uk)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/coolcomponents.co.uk)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/coolcomponents.co.uk)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

### CODE REVIEW

**Comment by accept-bitcoin-cash** [comment]
Processed and ready to be evaluated.

**Comment by EchterAgo** [comment]
Hmmm, right after I commented :\

**Comment by kenman345** [comment]
@EchterAgo  closed this why?
was it included in the merge I did? Shall we delete this branch?

**Comment by EchterAgo** [comment]
Yes, this was included in the pr, it's added not already.

**Pull request closed without merging**
