### PR TITLE
Add 'TEXGROUPITALIA' to the 'Abbigliamento Professionale' category

### PR DESCRIPTION
**Pull request by accept-bitcoin-cash**
Requesting to add 'TEXGROUPITALIA' to the 'Abbigliamento Professionale' category. 

Details follow: 
```yml 
- name: TEXGROUPITALIA
  url: https://www.texgroupitalia.com
  img: TEXGROUPITALIA.png 
  bch: true
  btc: true
  othercrypto: true
  twitter: texgroupitalia
  email_address: ordini@texgroupitalia.com
  region: eu
  country: IT
  city: Napoli
```

Resources for adding this merchant:
Logo Provided:
ProvidedLogoURL
Twitter Profile Image (48x48):
TwitterProfileImageURL
[Link to TEXGROUPITALIA](https://www.texgroupitalia.com)
If needed, try the twitter handles profile image: [twitter.com/texgroupitalia](https://twitter.com/texgroupitalia)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/www.texgroupitalia.com](https://www.alexa.com/siteinfo/www.texgroupitalia.com)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/www.texgroupitalia.com](https://www.scamadviser.com/check-website/www.texgroupitalia.com)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/www.texgroupitalia.com](https://www.trustpilot.com/review/www.texgroupitalia.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

### CODE REVIEW

**Comment by accept-bitcoin-cash** [comment]
Processing

**Comment by EchterAgo** [comment]
SSL certificate is invalid, issued to aruba.it

**Comment by EchterAgo** [comment]
lang: it

Their shop link goes to ebay

**Comment by EchterAgo** [comment]
I'm not quite sure what they accept crypto for and my Italian is very lacking. I'll send them an email.

**Comment by EchterAgo** [comment]
No response so far, closing for now.

**Pull request closed without merging**
