### PR TITLE
Save some bytes by linking to fb.com instead of facebook.com

### PR DESCRIPTION
**Pull request by EchterAgo**

### CODE REVIEW

**Comment by kenman345** [comment]
Saving a few bytes may not be the best thing. I've done this in the past locally and it means when users click the link they are getting redirected before the page resolves. 

Can you put pre/post change compiled page numbers in here please.

**Comment by EchterAgo** [comment]
I don't really know what you mean by compiled page numbers.

**Comment by kenman345** [comment]
when you run `bundle exec jekyll build` what is the full size of your `_site` folder before and after this PR?

**Comment by EchterAgo** [comment]
9303255 bytes before, 9289443 bytes after. A reduction of 13812 bytes.

**Comment by kenman345** [comment]
since this part of the page would not be lazy loaded, 13kb seems small especially between the three main pages, so i'm conflicted about do or do not. I am okay either way, I just dont think that small amount is going to make a difference since thats the entire folder we're talking about

**Comment by EchterAgo** [comment]
Yea, probably not worth it. Likely even less after gzip compression. Closing.

**Pull request closed without merging**
