### PR TITLE
Add 'Lushes Curtains' to the 'Retail' category

### PR DESCRIPTION
**Pull request by accept-bitcoin-cash**
Requesting to add 'Lushes Curtains' to the 'Housewares/ Home Decor' category. 

Details follow: 
```yml 
- name: Lushes Curtains
  url: https://www.lushescurtains.com/
  img: LushesCurtains.png
  bch: true
  btc: true
  othercrypto: true
  twitter: lushescurtains
  facebook: lushescurtains
  email_address: joe@lushescurtains.com
  country: US
  city: Global
  doc: https://twitter.com/LushesCurtains/status/1124391852071895045
  exceptions:
    text: "Just chose Coinbase Commerce at checkout to pay with Bitcoin Cash"
```

Resources for adding this merchant:
Logo Provided:
ProvidedLogoURL
Twitter Profile Image (48x48):
TwitterProfileImageURL
Facebook Profile Image:
FacebookProfileImageURL
[Link to Lushes Curtains](https://www.lushescurtains.com/)
Check their Twitter Page: [twitter.com/lushescurtains](https://twitter.com/lushescurtains)
Check their Facebook Page: [fb.com/lushescurtains](https://fb.com/lushescurtains)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.lushescurtains.com/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.lushescurtains.com/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.lushescurtains.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by Twitter user [lushescurtains](https://twitter.com/lushescurtains/), be sure to send out a tweet when this request has been added.

### CODE REVIEW

**Comment by accept-bitcoin-cash** [comment]
Processed and ready to be evaluated.

**Comment by kenman345** [comment]
@echterago shall I consider anything you’re processing is legit and review them?

**Comment by EchterAgo** [comment]
@kenman345 I'm usually processing before I review, but in this specific case I know this is a good listing already.

**Comment by kenman345** [comment]
Just go ahead and take care of them, I’m headed to bed but would love if we
had some more listings for next weeks release

**Pull request merged**
