### PR TITLE
Batch update

### PR DESCRIPTION
**Pull request by EchterAgo**

### CODE REVIEW

**Comment by kenman345** [comment]
why no merge? Adding more?

**Comment by EchterAgo** [comment]
It's not really a nice batch yet. I want to change some more listings, but
I am cooking right now. If you want you can merge it.

**Comment by EchterAgo** [comment]
Ready for review

**Comment by kenman345** [comment]
Completely unnecessary. Let’s not keep track of that. It’s just gonna add bloat.

**Comment by EchterAgo** [comment]
Ok, I'll remove it from the commit.

**Comment by EchterAgo** [comment]
Yea, agreed. Would be hard to keep track of and also sometimes it depends on the amount.

**Pull request merged**
