### PR TITLE
Add 'Sherilyn Shop' to the 'Apparel' category

### PR DESCRIPTION
**Pull request by accept-bitcoin-cash**
Requesting to add 'Sherilyn Shop' to the 'Bags and Shoes' category. 

Details follow: 
```yml 
- name: Sherilyn Shop
  url: https://SherilynShop.com
  img: SherilynShop.png
  bch: true
  btc: true
  othercrypto: true
  facebook: sherilynshop
  email_address: sherilynshopofficial@gmail.com
  country: US
```

Resources for adding this merchant:
Facebook Profile Image:
FacebookProfileImageURL
[Link to Sherilyn Shop](https://SherilynShop.com)
Check their Facebook Page: [fb.com/sherilynshop](https://fb.com/sherilynshop)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/SherilynShop.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/SherilynShop.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/SherilynShop.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

### CODE REVIEW

**Comment by accept-bitcoin-cash** [comment]
Processed and ready to be evaluated.

**Comment by EchterAgo** [comment]
I'm not sure anymore about the drop shipping claim, they only offer US shipping.

**Comment by EchterAgo** [comment]
Hmmmm, "Standard shipping (12-21 days)" for domestic shipping?

**Comment by EchterAgo** [comment]
Uses Coinbase Commerce

**Comment by kenman345** [comment]
are we merging this @EchterAgo ?

**Comment by EchterAgo** [comment]
Te can. At least drop shippers "deliver". I think last time I couldn't go through the order process, but I've not succeeded. Still needs the drop shipper warning, which I will add.

**Comment by EchterAgo** [comment]
I don't think I understand what it is complaining about :\

**Comment by kenman345** [comment]
not sure about this but trying to make things mergable

**Pull request merged**
