### PR TITLE
Large refactor of code structure/templating

### PR DESCRIPTION
**Pull request by t0p0lin0**
This branch cleans up a lot of re-used code with intentions to make adding additional pages much easier in the future. Currently, it differentiates between the 'home' and 'adult' pages. It also has some separate commits which remove unused/unnecessary layouts and includes/partials.

_Please pull this branch locally and test everything while reviewing!_ There are some substantial, though simple changes, however I have tested all successfully myself.

### CODE REVIEW

**Comment by t0p0lin0** [comment]
Adding the *DO NOT MERGE* label, because I am working on implementing a _donations_ listing page, after having refactored the template logic. This will also help to implement #653 and #376 -- I will remove the label when it is fit to merge. Thanks.

**Comment by kenman345** [comment]
May wish to move Wikipedia and frostwire to these.

Also, I pushed an update to the verify.rb script to include the sections.yml page from this.

**Comment by kenman345** [comment]
@t0p0lin0 do not worry about the small allowed to fail script reports from Travis for Push builds. Only the errors relating to your new additions matter since the rest are fixed in master and do not appear to be included in whats being tested by the Travis builds. 

If you look at the PR Travis Build, that brings in the changes present in master and show you what the combination of Master and your branch is. But I'll take care of those once we are not blocked here and the other PRs are closed.

**Comment by kenman345** [comment]
I forced the last commit to have a build on travis run against the latest master. Once this gets done we'll have 256 listings accepting BCH.

I think We may need to ask that @jrkong revise the script to reflect only the main page, maybe adjusting so we can have multiple outputs for it. Like maybe a stats yml file that we track the section, site count and site supporting BCH count and the script handles updating those so we can use them insted of it generating the html.

@jrkong if you do a revision of the script, talk with me, I got some ideas about how to make your life easier I am just wiped and am headed to bed now.

**Comment by kenman345** [comment]
I was thinking we need to link to the secondary pages better. Maybe we do side by side buttons like the merchant and customer buttons at the bottom but near the top to libk through to the other pages. If we added a pages.yml like I suggested for @jrkong s script to track listings per page, then we could also use that to identify the pages that’s not the current one and build those buttons.

And while we’re at it we should make the count at the bottom based off those numbers to bring it all together

**Comment by kenman345** [comment]
note: Closes #625 with the icon change done in Commit e55e0ddff9ea9c30fc3bfb15b8edb117faa47193

**Comment by kenman345** [comment]
So here's what I've done now:
- I threw in some better validations around the verify.rb script we run. It shall now verify and throw an error if the image is over 2500 bytes but it will not be a hard stop for a PR to be merged unless its over 3000 bytes. We can up that a bit though, but its pretty fair for now.

- We now run `bundle exec rake` on the must pass job of the travis builds. This will run the HTML Proofer like we were already doing, but also the Verify.rb script and rubocop which validates some of the linting we need. Rubocop wont ever be a problem for anyone adding a new listings, it only helps when we refactor the ruby scripts and rakefile.

- I went into the branch protection settings for our repository and enabled the checks to be required to pass for Travis-CI before a merge. We can roll it back if it becomes a problem but our script now gives a lot of information and I am going to be monitoring the twofactorauth repository and @stephengroat to see if we can identify a tool to add into the comments of a PR the failure reasons from Travis.

**Pull request merged**
