### PR TITLE
Add 'BA.net AdBlock VPN' to the 'Security' category

### PR DESCRIPTION
**Pull request by accept-bitcoin-cash**
Requesting to add 'BA.net AdBlock VPN' to the 'AdBlock VPN Provider' category. 

Details follow: 
```yml 
- name: BA.net AdBlock VPN
  url: https://ba.net/adblockvpn
  img: BAnetAdBlockVPN.png
  bch: true
  btc: false
  othercrypto: false
  email_address: adblock@ba.net
```

Resources for adding this merchant:
Logo Provided:
ProvidedLogoURL
[Link to BA.net AdBlock VPN](https://ba.net/adblockvpn)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/ba.net/adblockvpn)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/ba.net/adblockvpn)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/ba.net/adblockvpn)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

### CODE REVIEW

**Comment by accept-bitcoin-cash** [comment]
Processed

**Comment by accept-bitcoin-cash** [comment]
To use the bot, comment with a valid command one any issue or PR that has a section/[category] label applied to it. Instructions on sentence structure and commands are listed below.

Commands should be formatted in the following manner:
`/ABCBot [action] [arg1] [arg2]`

Available Commands/Arguments:
```
/ABCBot image [image_name] [image_url]
  -- Adds image to PR
/ABCBot process
/ABCBot process [category]
  -- Opens PR for listing.
  -- When used with optional parameter, adds in the category label to listing.
/ABCBot toggle [listing name: value] [btc|bch|bsv|othercrypto] ...
  -- Opens PR for listing to be updated with toggled values for cryptocurrency tracking.
  -- This will accept multiple final parameters as long as they are of the right types.
/ABCBot remove [listing name: value]
  -- Opens PR for listing to be removed.
/ABCBot help
```

**Comment by EchterAgo** [comment]
/ABCbot image BAnetAdBlockVPN.png https://i.imgur.com/XGf4aEw.png

**Comment by accept-bitcoin-cash** [comment]
Saved BAnetAdBlockVPN.png to img/security folder.

**Pull request merged**
