### PR TITLE
Add 'BCH Club' to the 'Social' category

### PR DESCRIPTION
**Pull request by accept-bitcoin-cash**
Requesting to add 'BCH Club' to the 'Social' category. 

Details follow: 
```yml 
- name: BCH Club
  url: https://bch.club/
  img: BCHClub.png
  bch: true
  btc: false
  othercrypto: false
  email_address: hongli.wang@bch.club
  region: as
  country: CN
  doc: https://bch.club/index.php?app=team&mod=Forum&act=detail&topic_id=215&team_id=1
```

Resources for adding this merchant:
[Link to BCH Club](https://bch.club/)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/bch.club/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/bch.club/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/bch.club/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

### CODE REVIEW

**Comment by kenman345** [comment]
We should get some clarification on how they accept BCH but this does seem BCH specific, its just whether or not its a service or a news source in which case it might be a donations listing instead of a place to spend.

**Comment by kenman345** [comment]
/ABCbot reprocess 
giving that a try, not sure if I made that a thing yet

**Comment by accept-bitcoin-cash** [comment]
Processed

**Comment by kenman345** [comment]
Reprocess apparently didnt fix it entirely, so I did it manually

**Comment by EchterAgo** [comment]
Just got an email reply, apparently there are rewards where you can earn BCH. I think they also sell tickets for BCH, sent another email asking for clarification.

**Pull request merged**
