### PR TITLE
Add AstrillVPN

### PR DESCRIPTION
**Pull request by EchterAgo**
Astrill accepts BCH through BitPay and Coinify

### CODE REVIEW

**Comment by EchterAgo** [comment]
Not sure why the build is failing, the log message seems to not have anything to do with what I changed. I tested the changes locally and they worked fine.

**Comment by kenman345** [comment]
We don’t allow the same url to be within the same section. https://anonine.com Appears literally in the listing above it. Please change out the url field to the proper website

**Comment by kenman345** [comment]
Sorry if that sounded harsh, just woke up to this and on my phone. But it appears you did not put in an acceptable url for your listing so it of course will fail the build to conform to our consistency guidelines. 

Please fix and we will be happy to merge this in to be added to the site with our next deploy

**Comment by kenman345** [comment]
Yea, seems the second line of your commit for the listing should be `url: https://www.astrill.com` and not `url: https://anonine.com` as that is the same url as the listing above it.

Our build test script can be run locally to verify you made the right change. 
`Ruby verify.rb`

**Comment by EchterAgo** [comment]
Arr, damn. I forgot to replace the URL :\ Sorry, I will double check this next time.

**Comment by kenman345** [comment]
All good. Your situation made me realize that I could try and parse out and display those errors better. Any other error would've displayed a little better, but those are a bit tricky

**Comment by kenman345** [comment]
@EchterAgo I was working on some edits to the verify.rb script that gave the error. What do you think about the following output in terms of being more direct about the error:

errormsg

With that, it added in the name of the listing its using,

**Comment by EchterAgo** [comment]
Looks good to me

**Pull request merged**
