### PR TITLE
Add 'SMT' to the 'Cryptoservices' category

### PR DESCRIPTION
**Pull request by accept-bitcoin-cash**
Requesting to add 'SMT' to the 'Cryptoservices' category. 

Details follow: 
```yml 
- name: SMT
  url: https://smt.ua/
  img: SMT.png
  bch: true
  btc: true
  othercrypto: true
  region: eu
  country: UA
```

Resources for adding this merchant:
[Link to SMT](https://smt.ua/)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/smt.ua/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/smt.ua/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/smt.ua/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

### CODE REVIEW

**Comment by accept-bitcoin-cash** [comment]
To use the bot, comment with a valid command one any issue or PR that has a section/[category] label applied to it. Instructions on sentence structure and commands are listed below.

Commands should be formatted in the following manner:
`/ABCBot [action] [arg1] [arg2]`

Available Commands/Arguments:
```
/ABCBot image [image_name] [image_url]
  -- Adds image to PR
/ABCBot process
/ABCBot process [category]
  -- Opens PR for listing.
  -- When used with optional parameter, adds in the category label to listing.
/ABCBot toggle [listing name: value] [btc|bch|bsv|othercrypto] ...
  -- Opens PR for listing to be updated with toggled values for cryptocurrency tracking.
  -- This will accept multiple final parameters as long as they are of the right types.
/ABCBot remove [listing name: value]
  -- Opens PR for listing to be removed.
/ABCBot help
```

**Comment by kenman345** [comment]
/ABCBot image SMT https://pbs.twimg.com/profile_images/1067706465262145536/-J5UAt1I_400x400.jpg

**Comment by accept-bitcoin-cash** [comment]
Saved SMT.png to cryptoservices folder.

**Comment by EchterAgo** [comment]
What is going on here? I can merge this branch into master locally without problems.

**Comment by kenman345** [comment]
Not sure, mobile site says no problem trying to merge, want me to do it

**Comment by kenman345** [comment]
?

**Comment by EchterAgo** [comment]
Yes

**Comment by EchterAgo** [comment]
It tells me this:

> This branch cannot be rebased due to conflicts
> Rebasing the commits of this branch on top of the base branch cannot be performed automatically due to conflicts encountered while reapplying the individual commits from the head branch.

**Pull request merged**
