### PR TITLE
Add 'Savvy' to the 'Payments' category

### PR DESCRIPTION
**Pull request by accept-bitcoin-cash**
Requesting to add 'Savvy' to the 'Payments' category. 

Details follow: 
```yml 
- name: Savvy
  url: https://www.savvy.io/merchant
  img: Savvy.png
  bch: true
  btc: true
  othercrypto: true
  twitter: getsavvyio
  facebook: savvyio
  email_address: mark@savvy.io
  country: US
  doc: https://coinjournal.net/crypto-payment-processor-paybear-rebrands-to-savvy/
```

Resources for adding this merchant:
[Link to Savvy](https://www.savvy.io/merchant)
Check their Twitter Page: [twitter.com/getsavvyio](https://twitter.com/getsavvyio)
Check their Facebook Page: [fb.com/savvyio](https://fb.com/savvyio)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.savvy.io/merchant)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.savvy.io/merchant)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.savvy.io/merchant)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by @savvyio/savvy-samples
Request made by Twitter user [getsavvyio](https://twitter.com/getsavvyio/), be sure to send out a tweet when this request has been added.

### CODE REVIEW

**Comment by EchterAgo** [comment]
We should replace Paybear with this. I'll first try to figure out if `country: US` is accurate.

**Comment by EchterAgo** [comment]
According to this tweet they operate worldwide, so I'll remove the `country` tag:
https://twitter.com/getsavvyio/status/1106375711718162433

**Comment by kenman345** [comment]
approved, merge when you are done

**Comment by EchterAgo** [comment]
I will soon make another Batch Update PR which will add this and also remove PayBear.

**Comment by kenman345** [comment]
merge it or let you? I'd prefer you did

**Comment by EchterAgo** [comment]
Don't merge, it'll be closed by my pull request later without merging.

**Pull request closed without merging**
