### PR TITLE
Add 'BCH Videos' to the 'Archives' category

### PR DESCRIPTION
**Pull request by accept-bitcoin-cash**
Requesting to add 'BCH Videos' to the 'Archives' category. 

Details follow: 
```yml 
- name: BCH Videos
  url: https://www.bchvideos.com
  img: 
  email_address: microbuxx@gmail.com
  bch: Yes
  btc: No
  othercrypto: No
  doc: https://www.bchvideos.com
```

Resources for adding this merchant:
Logo Provided:
BCH Videos

[Link to BCH Videos](https://www.bchvideos.com)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/www.bchvideos.com](https://www.alexa.com/siteinfo/www.bchvideos.com)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/www.bchvideos.com](https://www.scamadviser.com/check-website/www.bchvideos.com)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/www.bchvideos.com](https://www.trustpilot.com/review/www.bchvideos.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

### CODE REVIEW

**Comment by kenman345** [comment]
No pressure to merge, just wanted to use this as a test of some new bot functionality. It should be all good now

**Comment by accept-bitcoin-cash** [comment]
To use the bot, apply the `ReadyForBot` label to the issue/PR after adding a comment with a valid command. Instructions on sentence structure and commands are listed below.

Commands should be formatted in the following manner:
/ABCBot [command] [arg1] [arg2]

Available Commands with arguments:
image [image_name] [image_url] -- Relies on category label being applied to issue.
help

**Comment by kenman345** [comment]
testing

**Comment by accept-bitcoin-cash** [comment]
To use the bot, apply the `ReadyForBot` label to the issue/PR after adding a comment with a valid command. Commands are processed once every 30 minutes, so be patient. Instructions on sentence structure and commands are listed below.

Commands should be formatted in the following manner:
`/ABCBot [action] [arg1] [arg2]`

Available Commands/Arguments:
`/ABCBot image [image_name] [image_url]` -- Relies on category label being applied to issue.
`/ABCBot help `

**Comment by kenman345** [comment]
another test

**Comment by kenman345** [comment]
test

**Comment by accept-bitcoin-cash** [comment]
To use the bot, apply the `ReadyForBot` label to the issue/PR after adding a comment with a valid command. Commands are processed once every 30 minutes, so be patient. Instructions on sentence structure and commands are listed below.

Commands should be formatted in the following manner:
`/ABCBot [action] [arg1] [arg2]`

Available Commands/Arguments:
`/ABCBot image [image_name] [image_url]` -- Relies on category label being applied to issue.
`/ABCBot help `

**Pull request merged**
