### PR TITLE
Add 'Booking.com' to the 'Transport' category

### PR DESCRIPTION
**Pull request by accept-bitcoin-cash**
Requesting to add 'Booking.com' to the 'Transport' category. 

Details follow: 
```yml 
- name: Booking.com
  url: https://booking.com
  img: Bookingcom.png
  bch: true
  btc: true
  othercrypto: true
  twitter: bookingcom
  facebook: booking.com
  doc: https://news.bitcoin.com/travala-partners-with-booking-com-90000-crypto-accepting-destinations-added/
  exceptions:
    text: "Booking.com does not accept cryptocurrencies directly, but they have just partnered with Travala.com so that all of booking.com's listings will show up on Travala as well. In this way, any booking.com listing can be paid for with cryptocurrency, because Travala.com allows you to do that for all their listings. This partnership allows booking.com to get into the marketshare of cryptocurrency users."
```

Resources for adding this merchant:
[Link to Booking.com](https://booking.com)
Check their Twitter Page: [twitter.com/bookingcom](https://twitter.com/bookingcom)
Check their Facebook Page: [fb.com/booking.com](https://fb.com/booking.com)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/booking.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/booking.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/booking.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

### CODE REVIEW

**Comment by EchterAgo** [comment]
@kenman345 I believe this one needs Travis CI retried.

**Comment by kenman345** [comment]
Attempting from mobile but can rerun later if it doesn’t work

**Comment by kenman345** [comment]
@EchterAgo This one also needs Master merged in but will merge fine if approved and merged anyways.

**Comment by EchterAgo** [comment]
It looks like Booking.com does not accept cryptocurrency on their site, only on travala.com, which we have already listed under Transport and Accomodation. I would prefer not adding this.

> According to Travala the collaboration adds Booking.com’s accommodation listings to the Travala portal

**Comment by zquestz** [comment]
> It looks like Booking.com does not accept cryptocurrency on their site, only on travala.com, which we have already listed under Transport and Accomodation. I would prefer not adding this.
> 
> > According to Travala the collaboration adds Booking.com’s accommodation listings to the Travala portal

 I agree, if the site doesn't take it directly they should not be listed.

**Pull request closed without merging**
