### PR TITLE
Batch update

### PR DESCRIPTION
**Pull request by EchterAgo**

### CODE REVIEW

**Comment by EchterAgo** [comment]
Still waiting on info from #1035 and Atlantis Labs regarding keyport.cash

**Comment by EchterAgo** [comment]
From Shravan Shandilya:

```
Sure. Thanks.
Name: Keyport,
Category: Communication,
Twitter: @keyportapp
Website: keyport.cash

Regards,
Shravan
```

**Comment by EchterAgo** [comment]
Ready for review

**Comment by kenman345** [comment]
I made an update simply because we should be going for completeness where possible for the crypto based tags. When I see missing tags, I end up verifying the missing ones. So its best to have it explicitly in there so we know we've at least recently checked it.

**Comment by EchterAgo** [comment]
Oh, I didn't know that. I will be adding all in the future.

**Comment by EchterAgo** [comment]
Can you give me a hint on how you add commits to others PRs?

**Comment by kenman345** [comment]
Thats why I added you as a contributor, so you can edit our PRS too. But basically, I use github UI and hit the edit button that looks like a pen. You can make a change and commit from there for some filetypes.

**Comment by EchterAgo** [comment]
Ah, thanks, good to know. I didn't think of that :)

**Comment by kenman345** [comment]
I've done a few PRs straight from the webpage. Not always recommended but I was limited in my means at those points.

**Pull request merged**
