### PR TITLE
Parse URL parameters for BCH-only filtering by default

### LINKED ISSUE #221: BCH-only filter active on page load
Check the URL hash and if set to something like `bch-only`, then activate the filter, so people can share links directly to the Bitcoin Cash only listings.

### PR DESCRIPTION
**Pull request by t0p0lin0**
i.e. https://acceptbitcoin.cash/#bch

Idea from https://www.reddit.com/r/btc/comments/78xcb4/you_can_now_filter_acceptbitcoincash_to_only/doxsnuf/ -- Resolves #221

### CODE REVIEW

**Comment by zquestz** [comment]
This would be better as a url parameter. https://acceptbitcoin.cash/?bch=true. Using the anchor is for links on the page, url params are for filters. =)

**Comment by kenman345** [comment]
url params are definitely the way it works when I do this type of thing.

**Comment by t0p0lin0** [comment]
Thanks for setting me straight fellas! This is the better, proper way to do it. Bonus is that it works with the category hash as well, i.e. https://acceptbitcoin.cash/?filter=bch#social opens up the Social section and shows only merchants accepting Bitcoin Cash. Please give it a shot and re-eval.

**Comment by kenman345** [comment]
is it not supposed to be acceptbitcoin.cash#social?filter=bch ? I am not recalling if thats the proper way or not. Looks good to me though. I know we have acceptbitcoin.cash#social working now so I dont want this to break any links out there already

**Comment by t0p0lin0** [comment]
@kenman345 -- I believe the URL parameter should come first, _then_ the anchor...at least, it works nicely this way in my implementation. Let's see what @zquestz thinks though.

**Pull request merged**
