### PR TITLE
Add 'Host1.no' to the 'Cloud computing / domains / web hosting' category

### PR DESCRIPTION
**Pull request by accept-bitcoin-cash**
Requesting to add 'Host1.no' to the 'Cloud computing / domains / web hosting' category. 

Details follow: 
```yml 
- name: Host1.no
  url: https://host1.no
  img: Hostno.png
  bch: true
  btc: true
  othercrypto: false
  twitter: host1no
  email_address: support@host1.no
  doc: Announcement for accepting Bitpay payments: https://blog.host1.no/nyheter/you-can-now-pay-with-bitcoins-on-host1-no/
```

Resources for adding this merchant:
Logo Provided:
ProvidedLogoURL
Twitter Profile Image (48x48):
TwitterProfileImageURL
[Link to Host1.no](https://host1.no)
Check their Twitter Page: [twitter.com/host1no](https://twitter.com/host1no)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/host1.no)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/host1.no)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/host1.no)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

### CODE REVIEW

**Comment by accept-bitcoin-cash** [comment]
Processed and ready to be evaluated.

**Comment by kenman345** [comment]
What exactly was the build issue? Sounds like I have something to fix

**Comment by kenman345** [comment]
Ah, I think the doc section just needed to be wrapped in quotes

**Comment by EchterAgo** [comment]
Shouldn't `doc` always be a URL?

**Comment by EchterAgo** [comment]
In CONTRIBUTING.md it says:

- `doc` -- Documentation/Help Guides (URL)

**Comment by EchterAgo** [comment]
We have some listings that are not a URL:

```
$ grep doc: _data/* | grep -v 'doc: http'
_data/developer.yml:  doc: disabled for now as per https://github.com/bountysource/core/issues/1162
_data/hosting.yml:  doc:
_data/utilities.yml:  doc: "Note: several other country domains: fr/de/at/it/es exist as well"
```

**Comment by EchterAgo** [comment]
Those listings generate broken links, we should fix them.

**Comment by kenman345** [comment]
Will do thanks!

**Comment by EchterAgo** [comment]
I already fixed it. Can you add your review here?

**Comment by EchterAgo** [comment]
On, just realized I can put my review as well.

**Pull request merged**
