### PR TITLE
Add 'SD Bullion' to the 'Jewelry' category

### PR DESCRIPTION
**Pull request by accept-bitcoin-cash**
Requesting to add 'SD Bullion' to the 'Jewelry' category. 

Details follow: 
```yml 
- name: SD Bullion
  url: https://sdbullion.com
  img: SDBullion.png
  bch: true
  btc: true
  othercrypto: false
  twitter: sdbullion
  facebook: sdbullion
  email_address: sales@sdbullion.com
  doc: https://sdbullion.com/payment-pricing
```

Resources for adding this merchant:
[Link to SD Bullion](https://sdbullion.com)
Check their Twitter Page: [twitter.com/sdbullion](https://twitter.com/sdbullion)
Check their Facebook Page: [fb.com/sdbullion](https://fb.com/sdbullion)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/sdbullion.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/sdbullion.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/sdbullion.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

### CODE REVIEW

**Comment by kenman345** [comment]
you approved it but no merge?

**Comment by EchterAgo** [comment]
I don't know why, but it tells me I need approval before merging.

**Comment by kenman345** [comment]
you on mobile or something? whatever, I'll merge since i dont see that

**Comment by EchterAgo** [comment]
Yes, on mobile. I'm not sure why, but I had this happen on mobile before.

**Pull request merged**
