### PR TITLE
Cleaned up and rebase fixes by simonri

### LINKED ISSUE #1582: "Add a site or correction" button seems to not work
On the lower right we have the "Add a site or correction" button represented by a white plus in a green circle. It is not doing anything when I click it.

image

### PR DESCRIPTION
**Pull request by EchterAgo**
Closes #1642
Closes #1582

### CODE REVIEW

**Comment by EchterAgo** [comment]
@kenman345 review please

**Comment by EchterAgo** [comment]
@simonri you might want to take a look.

**Comment by EchterAgo** [comment]
I'll rebase this.

**Comment by EchterAgo** [comment]
@kenman345 rebased and tests passing.

**Comment by zquestz** [comment]
@kenman345 did you want to review? I looked and it seemed right. =)

**Pull request merged**
