### PR TITLE
Add 'CryptoServers - Cloud KVM servers' to the 'Hosting' category

### PR DESCRIPTION
**Pull request by accept-bitcoin-cash**
Requesting to add 'CryptoServers - Cloud KVM servers' to the 'Hosting' category. 

Details follow: 
```yml 
- name: CryptoServers - Cloud KVM servers
  url: https://cryptoservers.net
  img: CryptoServersCloudKVMservers.png
  bch: true
  btc: true
  othercrypto: true
  email_address: support@cryptoservers.net
  region: eu
```

Resources for adding this merchant:
[Link to CryptoServers - Cloud KVM servers](https://cryptoservers.net)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/cryptoservers.net)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/cryptoservers.net)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/cryptoservers.net)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

### CODE REVIEW

**Comment by EchterAgo** [comment]
too new

**Comment by accept-bitcoin-cash** [comment]
To use the bot, comment with a valid command one any issue or PR that has a section/[category] label applied to it. Instructions on sentence structure and commands are listed below.

Commands should be formatted in the following manner:
`/ABCBot [action] [arg1] [arg2]`

Available Commands/Arguments:
```
/ABCBot image [image_name] [image_url]
  -- Adds image to PR
/ABCBot process
/ABCBot process [category]
  -- Opens PR for listing.
  -- When used with optional parameter, adds in the category label to listing.
/ABCBot toggle [listing name: value] [btc|bch|bsv|othercrypto] ...
  -- Opens PR for listing to be updated with toggled values for cryptocurrency tracking.
  -- This will accept multiple final parameters as long as they are of the right types.
/ABCBot remove [listing name: value]
  -- Opens PR for listing to be removed.
/ABCBot help
```

**Comment by kenman345** [comment]
/ABCBOT image CryptoServersCloudKVMservers.png https://cryptoservers.net/favicon-32x32.png

**Comment by accept-bitcoin-cash** [comment]
Saved CryptoServersCloudKVMservers.png to img/hosting folder.

**Comment by kenman345** [comment]
@EchterAgo Getting some of these branches in a mergeable state for whenever they are able to be reviewed properly

**Comment by EchterAgo** [comment]
They are integrated with myvpn.run, which does have some reputation. From the looks of the sites I think there is some association.

**Pull request merged**
