### PR TITLE
Fixed up some listings to be more accurate

### PR DESCRIPTION
**Pull request by kenman345**

### CODE REVIEW

**Comment by EchterAgo** [comment]
Good find that ProtonMail doesn't actually accept BTC payment. Did this change recently?

**Comment by EchterAgo** [comment]
Yes, they do accept Bitcoin for payments:
image

**Comment by EchterAgo** [comment]
Same for ProtonVPN

**Comment by EchterAgo** [comment]
I think we should mention that BTC can not be used to create new accounts in the exceptions. Note that I actually created a free account and after that I could pay with Bitcoin.

**Comment by kenman345** [comment]
Have you tried using that option? Last time I tried it wouldnt let me, even though it was a dropdown option

**Comment by EchterAgo** [comment]
I'll try it. Will update soon.

**Comment by EchterAgo** [comment]
I can pay with BTC on Protonmail.

**Comment by kenman345** [comment]
@EchterAgo  all fixed and fixed up an issue that was reported by a user. If you can take a look that would be great but i may merge this before the weekly build happens.

**Comment by kenman345** [comment]
from `u/youarelovedSOmuch` on reddit in a private message:

> Hey Kenman, been having a problem on the acceptbitcoin.cash website with the Submit new merchant button. Have you tried it in a while? The only way I can get the submission form to work is by manually going directly to acceptbitcoin.cash/add. The button will not work anymore. I have tried using multiple browsers. Looking at it closer, it appears the link for acceptbitocin.cash/add only shows up if I hover over just the right spot on the button. That would explain why it's not working.

But I noticed I had a similar issue with clicking it locally so I figured this change would fix it so the entire `a` anchor tag is the button, preventing any zone hitting issues.

**Comment by EchterAgo** [comment]
Seems like it was working for me only because of a browser extension, it doesn't work with extensions disabled.

**Pull request merged**
