### PR TITLE
Add 'Spincy Watches' to the 'Jewelry' category

### PR DESCRIPTION
**Pull request by accept-bitcoin-cash**
Requesting to add 'Spincy Watches' to the 'Jewelry' category. 

Details follow: 
```yml 
- name: Spincy Watches
  url: https://spincy.com
  img: SpincyWatches.png
  bch: true
  btc: true
  othercrypto: true
  email_address: garydeed@protonmail.com
  doc: https://www.reddit.com/r/btc/comments/cdp9kq/my_website_now_supports_bitcoin_cash/
```

Resources for adding this merchant:
[Link to Spincy Watches](https://spincy.com)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/spincy.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/spincy.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/spincy.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

### CODE REVIEW

**Comment by EchterAgo** [comment]
They are selling expensive watches. While the domain is old, the site is pretty new. The company in the terms of service, "Beautynic SUN Dry Cure", only has one search result on `exchangemarketplace.com` with a title of "All Listings | Ecommerce Websites & Businesses for Sale". I don't think we should add this right now, but I'll keep an eye on it.

**Comment by kenman345** [comment]
/abcbot image SpincyWatches.png https://cdn.shopify.com/s/files/1/0079/4863/2146/files/New_Project_1_32x32.png?v=1561073952

**Comment by accept-bitcoin-cash** [comment]
Unable to add SpincyWatches.png to img/jewelry.

**Comment by kenman345** [comment]
not sure about the quality of the site just making it mergable

**Comment by kenman345** [comment]
/abcbot image SpincyWatches.png https://cdn.shopify.com/s/files/1/0079/4863/2146/files/New_Project_1_32x32.png

**Comment by accept-bitcoin-cash** [comment]
Unable to add SpincyWatches.png to img/jewelry.

**Comment by kenman345** [comment]
/abcbot image SpincyWatches.png http://cdn.shopify.com/s/files/1/0079/4863/2146/files/New_Project_1_32x32.png

**Comment by accept-bitcoin-cash** [comment]
Unable to add SpincyWatches.png to img/jewelry.

**Comment by kenman345** [comment]
IDK about this one. No Social links for Twitter or Facebook yet the icons on the site are there.

**Comment by kenman345** [comment]
/ABCBot image SpincyWatches.png https://i.imgur.com/ta62CTj.jpg?3

**Comment by accept-bitcoin-cash** [comment]
Saved SpincyWatches.png to img/jewelry folder.

**Comment by EchterAgo** [comment]
Allegations of fraud, low quality watches: https://www.reddit.com/r/Bitcoin/comments/cmldfe/spincy_watches_are_garbage/

**Pull request closed without merging**
