### PR TITLE
Add 'Black Ink Coffee Company' to the 'Food and Drink' category

### PR DESCRIPTION
**Pull request by accept-bitcoin-cash**
Requesting to add 'Black Ink Coffee Company' to the 'Food and Drink' category. 

Details follow: 
```yml 
- name: Black Ink Coffee Company
  url: https://blackinkcoffee.com
  img: BlackInkCoffeeCompany.png 
  bch: true
  btc: true
  othercrypto: true
  twitter: bicoffeecompany
  facebook: blackinkcoffeecompany
  email_address: info@blackinkcoffee.com
  doc: https://commerce.coinbase.com/charges/3JG3MQDP
```

Resources for adding this merchant:
Twitter Profile Image (48x48):
TwitterProfileImageURL
[Link to Black Ink Coffee Company](https://blackinkcoffee.com)
If needed, try the twitter handles profile image: [twitter.com/bicoffeecompany](https://twitter.com/bicoffeecompany)
If needed, try the facebook handles profile image: [fb.com/blackinkcoffeecompany](https://fb.com/blackinkcoffeecompany)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/blackinkcoffee.com](https://www.alexa.com/siteinfo/blackinkcoffee.com)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/blackinkcoffee.com](https://www.scamadviser.com/check-website/blackinkcoffee.com)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/blackinkcoffee.com](https://www.trustpilot.com/review/blackinkcoffee.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

### CODE REVIEW

**Comment by accept-bitcoin-cash** [comment]
Processing

**Comment by kenman345** [comment]
This is a bit weird, they're a kickstarter? I dont think we should list them until they actually have a shipping product on their site. Closing for now. 

@EchterAgo dont we have a reminder bot thing? maybe check back in 6 months?

**Comment by EchterAgo** [comment]
Yea, we should wait until they actually have something.

/remind me in 6 months

**Comment by EchterAgo** [comment]
Hrmm, that doesn't seem to be working anymore.

**Comment by EchterAgo** [comment]
new bot?

**Comment by kenman345** [comment]
no, was just trying again

**Comment by EchterAgo** [comment]
The bot seems to be not operating anymore, the website is dead.

https://github.com/apps/reminders

**Comment by kenman345** [comment]
While I hate seeing things look stale, I dont want to leave a branch just hanging, so lets leave this open at least for a bit to make sure we dont forget it

**Comment by EchterAgo** [comment]
I don't think this makes things look stale. It looks like this is why the reminder bot is not working here: https://github.com/probot/reminders/issues/38

**Comment by EchterAgo** [comment]
Still "Coming Soon"

**Comment by kenman345** [comment]
Yea, i';ve been checking in on this and its still not out yet. might decide to opt to close this and delete the branch. Kickstarter still hasnt launched and its not even a guarantee that they will ever open/do business

**Comment by EchterAgo** [comment]
Their Kickstarter is live now and looks like it will succeed:

https://www.kickstarter.com/projects/blackinkcoffee/black-ink-coffee-company

**Pull request merged**
