### PR TITLE
Add 'Idle-Empire' to the 'Gaming' category

### PR DESCRIPTION
**Pull request by accept-bitcoin-cash**
Requesting to add 'Idle-Empire' to the 'Gaming' category. 

Details follow: 
```yml 
- name: Idle-Empire
  url: https://www.idle-empire.com
  img: IdleEmpire.png
  bch: true
  btc: true
  othercrypto: true
  twitter: csgoidleempire
  facebook: idle.empire.csgo
  email_address: admin@idle-empire.com
  doc: https://blog.idle-empire.com/coinbase-withdrawals-integrated/
  exceptions:
    text: "Users can earn virtual credits by watching videos, completing tasks, mining cryptocurrencies, and many other things. Those credits can then be redeemed for Bitcoin Cash, other cryptocurrencies, and gaming rewards."
```

Resources for adding this merchant:
[Link to Idle-Empire](https://www.idle-empire.com)
Check their Twitter Page: [twitter.com/csgoidleempire](https://twitter.com/csgoidleempire)
Check their Facebook Page: [fb.com/idle.empire.csgo](https://fb.com/idle.empire.csgo)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.idle-empire.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.idle-empire.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.idle-empire.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by @chescos

### CODE REVIEW

**Comment by EchterAgo** [comment]
Not sure if gaming is the right category here. Crypto Services maybe.

**Comment by kenman345** [comment]
not entirely sure if this is the type of site we list, but yea, cryptoservices seems right.

**Comment by kenman345** [comment]
i dont know if this is a site we list because it appears you earn BCH not spend it. With gambling sites you are spending while also potentially winning BCH, but in this case its a bit like a faucet, which we have not listed in the past.

**Comment by kenman345** [comment]
opened #1501 because I'm lazy.

**Pull request closed without merging**
