### PR TITLE
added Nonno Angelo Pizza in Tel Aviv

### PR DESCRIPTION
**Pull request by torusJKL**
New Pizza place that accepts Bitcoin Cash since this years Bitcoin Pizza Day.
https://twitter.com/torusJKL/status/998981543984029696

### CODE REVIEW

**Comment by EchterAgo** [comment]
Looks good. Both the pizza and the listing.

**Comment by EchterAgo** [comment]
Maybe add your tweet as the doc link?

**Comment by torusJKL** [comment]
Sure.
I didn't know if a third party tweet is good enough as doc link.

**Comment by EchterAgo** [comment]
We have listings like that already, it should be fine.

**Pull request merged**
