### PR TITLE
Batch update

### PR DESCRIPTION
**Pull request by EchterAgo**

### CODE REVIEW

**Comment by kenman345** [comment]
@EchterAgo this PR is failing because of the latest Rubocop and fixes to our verify script being needed unless we actually configure it away from stock settings. 

If you run `bundle update` it should pull in the newest rubocop.
Then run `rubocop --auto-correct` (I ran with `bundle exec` in front) and then it will automatically correct the script. Please add that to this PR so it passes and we gen the fix into master.

**Comment by kenman345** [comment]
@EchterAgo did it myself on your repo so its part of a PR. Once it passes I'll merge it into master.

**Comment by EchterAgo** [comment]
Thanks, was also just looking into it. I'll do some more updates the next few days. I plan to get the backlog sorted. Did you see what I wrote about public rules in Slack?

**Comment by kenman345** [comment]
I have not been looking at slack or this repo recently. I will be trying to be better about it though. Working on a first year anniversary write-up to post in the next few days.

**Comment by EchterAgo** [comment]
I'll make an issue for it.

**Pull request merged**
