### PR TITLE
Batch update

### PR DESCRIPTION
**Pull request by EchterAgo**

### CODE REVIEW

**Comment by EchterAgo** [comment]
What is going on here? Raking locally I do not see any errors.

**Comment by kenman345** [comment]
It’s failing on an HTML validation issue. I am unsure what it is yet, I can take a look if it’s not that ARTLy thing I’m an hour

**Comment by EchterAgo** [comment]
Yea, ARTly seems to be it. It does not escape the ampersand in the generated HTML. Is this a problem with the generator or should I use &amp; in the .yml file?

**Comment by kenman345** [comment]
Fix the listing for now I’ll play with fixing the HTML later

**Comment by EchterAgo** [comment]
I think putting it in quotes would be a better solution than putting HTML in the yml, if that works.

**Comment by kenman345** [comment]
seems putting it into quotes works. Want me to put it back?

**Comment by EchterAgo** [comment]
Yes.

**Comment by kenman345** [comment]
I do wonder how my rake task will rewrite that....I'll try that out later. Make sure its all good. worst comes to worst I can fix it for when we generate the HTML

**Pull request merged**
