### PR TITLE
Added 3 new sites + added twitter/facebook for Futon Beds From Japan

### PR DESCRIPTION
**Pull request by hegjon**

### CODE REVIEW

**Comment by kenman345** [comment]
I'll fix it on my PR instead

**Comment by hegjon** [comment]
I could also remove _The_ from the name, I used the title on their homepage as the name

**Comment by kenman345** [comment]
This is already merged, and I fixed it on my PR.

I will add to my to-do to evaluate ignoring the "the" if possible, but not sure we can. Its more about keeping our repository clean than it is about any technical limitation.

Also, Are you allowed to make brnaches off our repo? I think you should be able to just not commit or merge to the protected branches. That will make fixing PRs of yours easier for us and also mean you can get builds for each branch push you do with Travis running on them.

**Comment by kenman345** [comment]
no naming conventions really, but i do the date and my username in it to keep things easy to identify for PRs of just new content additions

**Comment by hegjon** [comment]
I am not allowed to push
```
$ git push upstream hegjon-jan1
ERROR: Permission to acceptbitcoincash/acceptbitcoincash.git denied to hegjon.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by kenman345** [comment]
okay then, all is okay. I'll just pull down your fork sometime if I need to help on a PR

**Pull request merged**
