### PR TITLE
Added two merchants

### PR DESCRIPTION
**Pull request by hegjon**

### CODE REVIEW

**Comment by EchterAgo** [comment]
I think retail might be the wrong section for the Yacht service, Services or Transport maybe? Also, both vendors use BitPay, so both should have something like this:

```
  bch: true
  btc: true
  othercrypto: false
  keywords:
  - bitpay
  - bip70
```

You can also add this to the yacht service:

```
  doc: https://www.denisonyachtsales.com/denison-yacht-sales-now-accepting-bitcoin/
```

**Comment by hegjon** [comment]
> I think retail might be the wrong section for the Yacht service, Services or Transport maybe?

They sell boats, so they could be in the same category as car dealers, if we have any?

**Comment by hegjon** [comment]
> Also, both vendors use BitPay, so both should have something like this

Added

**Comment by hegjon** [comment]
Also added doc to the yacht service

**Comment by EchterAgo** [comment]
What do you think about the section for the Yacht service @kenman345 ? Everything else seems OK to me.

**Comment by EchterAgo** [comment]
Yes, next time I make a big update I will probably try to get the retail section split up a bit. I think we should put the yacht listing into services.

**Comment by kenman345** [comment]
Let’s go with that for now!

**Comment by hegjon** [comment]
Sure, I thought it was merged. Will move it now

**Pull request merged**
