### PR TITLE
Add 'Casa de Piedra' to the 'Food' category

### PR DESCRIPTION
**Pull request by accept-bitcoin-cash**
Requesting to add 'Casa de Piedra' to the 'Food/Beverages' category. 

Details follow: 
```yml 
- name: Casa de Piedra
  url: http://www.vinoscasadepiedra.com/sc_listaPrecios.php
  img: CasadePiedra.png
  bch: true
  btc: true
  othercrypto: false
  facebook: vinicolacasadepiedra
  email_address: administracion@vyva.mx
  region: na
  doc: http://www.vinoscasadepiedra.com
  exceptions:
    text: "Go to the "Pay in Bitcoin" tab."
```

Resources for adding this merchant:
Logo Provided:
ProvidedLogoURL
Facebook Profile Image:
FacebookProfileImageURL
[Link to Casa de Piedra](http://www.vinoscasadepiedra.com/sc_listaPrecios.php)
Check their Facebook Page: [fb.com/vinicolacasadepiedra](https://fb.com/vinicolacasadepiedra)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.vinoscasadepiedra.com/sc_listaPrecios.php)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.vinoscasadepiedra.com/sc_listaPrecios.php)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.vinoscasadepiedra.com/sc_listaPrecios.php)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

### CODE REVIEW

**Comment by accept-bitcoin-cash** [comment]
Processed and ready to be evaluated.

**Comment by EchterAgo** [comment]
I do not see a "Pay in Bitcoin" tab on their site. I will be sending an email to ask for confirmation.

**Comment by EchterAgo** [comment]
So far no response.

**Comment by EchterAgo** [comment]
Site is dead

**Pull request closed without merging**
