### PR TITLE
Add 'Alba Tools' to the 'Retail' category

### PR DESCRIPTION
**Pull request by accept-bitcoin-cash**
Requesting to add 'Alba Tools' to the 'Retail' category. 

Details follow: 
```yml 
- name: Alba Tools
  url: https://www.albatools.uk
  img: AlbaTools.png 
  bch: true
  btc: true
  othercrypto: true
  twitter: albatoolsuk
  facebook: albatoolsuk
  email_address: sales@albatools.uk
  exceptions: 
    text: "At checkout under payment method choose 'Bitcoin or other cryptocurrencies' and a list of cryptocurrencies accepted will appear."
```

Resources for adding this merchant:
Twitter Profile Image (48x48):
Alba Tools
[Link to Alba Tools](https://www.albatools.uk)
If needed, try the twitter handles profile image: [twitter.com/albatoolsuk](https://twitter.com/albatoolsuk)
If needed, try the facebook handles profile image: [fb.com/albatoolsuk](https://fb.com/albatoolsuk)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/www.albatools.uk](https://www.alexa.com/siteinfo/www.albatools.uk)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/www.albatools.uk](https://www.scamadviser.com/check-website/www.albatools.uk)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/www.albatools.uk](https://www.trustpilot.com/review/www.albatools.uk)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

### CODE REVIEW

**Comment by kenman345** [comment]
@EchterAgo I cannot reach the site but the travis CI can? And isitdownorjustme says its just me.

Twitter account seems new. I'm uuncertain about this one. I trust you can help with making a determination.

**Comment by EchterAgo** [comment]
It looks legitimate to me, but the site is down for me as well. I also used UK company registration search and found no match for Alba Tools, but they might be incorporated under a different name. Whois indicates the domain is active since February of 2017 and there is a snapshot on archive.org here https://web.archive.org/web/20171123235841/http://albatools.uk:80/

**Comment by EchterAgo** [comment]
Seems to be David Simpson trading:

https://webcache.googleusercontent.com/search?q=cache:eM5CSN3kjpwJ:https://www.albatools.uk/terms+&cd=2&hl=en&ct=clnk&gl=th

The address is a residential address in Edinburgh. Still no success finding the company registration. I sent them an email to their sales email telling them their site is down and we need it to be up to proceed with listing. I also found the owners medium account: https://medium.com/@davesbaits/responses

**Comment by EchterAgo** [comment]
My email to them bounced, relay not permitted.

**Pull request closed without merging**
