### PR TITLE
Update BuyCraft, they removed Bitcoin payments

### PR DESCRIPTION
**Pull request by EchterAgo**

### CODE REVIEW

**Comment by kenman345** [comment]
Mind putting some of these things into one PR next time? Its one thing if its a questionable addition but updating the info on a listing is 100% batchable.

**Comment by kenman345** [comment]
just finished going through all your PRs. Love the work but definitely batch a few next time. Travis-CI runs for each commit pushed, which is automatic when we merge. So right now we have tons of concurrent builds going and all trying to update the beta site when they finish. 

Thanks for all your hard work though, Its very much appreciated. If you have any questions feel free to reach out over our slack channel on btcchat

**Comment by EchterAgo** [comment]
Ok, will make a bigger pull request with separate commits next time, so we can still remove some changes that shouldn't go in. I would need an invite to btcchat, my email is derago@gmail.com

**Comment by kenman345** [comment]
invite sent. Just introduce yourself in the introductions channel and mention the #accept-Bitcoin-cash channel and needing an invite, I'll get you in the channel when I see that

**Pull request merged**
