### PR TITLE
swap image for clearer indicator image

### LINKED ISSUE #1187: Replace the "broken" image file used when a listing doesn't have an image with something else
When a listing does not have an image file an icon that seems to imply a broken image is used. When I see this it always makes me wonder if there is a problem with my internet connection or the website on first sight. It takes me a few milliseconds to remember that it means "no image" instead of "broken image", even though I work on the site regularly. Other users might not even realize that this does mean no image. We should consider replacing that with either a better symbol or even omitting the image circle completely for these listings.

### PR DESCRIPTION
**Pull request by kenman345**
@chaintip fixes #1187

### CODE REVIEW

**Comment by kenman345** [comment]
Sorry this took so long, kinda forgot about it. It makes a lot of sense to use an image like suggested, so I just went ahead and did it

**Comment by kenman345** [comment]
awesome!

**Comment by EchterAgo** [comment]
Hmmm, is @chaintip down at the moment?

**Comment by kenman345** [comment]
possibly?!?

**Comment by EchterAgo** [comment]
Just created an issue on their repo

**Comment by chaintip** [comment]
If this pull request is merged to fix issue [#1187](http://github.chaintip.org/acceptbitcoincash/acceptbitcoincash/issues/1187) first, @kenman345 will claim the `0.01029365 BCH`| `~   4.65 USD` [bounty](http://github.chaintip.org/chaintip/bounties/issues/46) and all future tips to the issue.

**Comment by kenman345** [comment]
@chaintip you're drunk! Its already merged

**Pull request merged**
