### PR TITLE
Add a progress bar which tracks ratio of sites supporting BCH

### PR DESCRIPTION
**Pull request by t0p0lin0**
*Note:* The output of the `count_support.html` partial is generated by `./scripts/python/bchAccepted.py` and should be run prior to each build (I will look into automating this via the Jekyll build scripts)

### CODE REVIEW

**Comment by t0p0lin0** [comment]
image

**Comment by t0p0lin0** [comment]
@jrkong specifically -- Please review the edits that I made to `bchAccepted.py` to ensure that the script still works accurately.

**Comment by deadr0ck** [comment]
Very nice work guys.

**Comment by t0p0lin0** [comment]
Ready to merge this, however it's imperative that the script be run to update the actual counts. @zquestz -- thoughts on how to best do this? I think it's only really essential prior to pushing a new release to production, however it would entail having the server/Docker setup run that one Python script prior to deployment.

Let's discuss options before we merge this one in. Thanks in advance!

**Comment by zquestz** [comment]
LGTM

**Pull request merged**
