### PR TITLE
Batch update

### PR DESCRIPTION
**Pull request by EchterAgo**

### CODE REVIEW

**Comment by EchterAgo** [comment]
There is still a long list left for this one :)

**Comment by kenman345** [comment]
Well, let me know if you need me to merge it, I think you can do it now if you've accepted the invite to the organization.

I'd like to be able to tag master for release to production tonight if we can get these merged in.

**Comment by EchterAgo** [comment]
We can merge the current state, I think I'm done for tonight, kind of tired and in need of a beer.

**Comment by kenman345** [comment]
done. did you accept org invite yet?

**Comment by EchterAgo** [comment]
Yes, I have.

**Pull request merged**
