### PR TITLE
Merge on or after April 25th - Update Mollie, they will stop accepting BTC

### PR DESCRIPTION
**Pull request by EchterAgo**
Mollie will discontinue Bitcoin payments in May, we should merge this then.

See https://www.reddit.com/r/btc/comments/bazxqq/dutch_payment_provider_mollie_has_stopped/ for details.

### CODE REVIEW

**Comment by EchterAgo** [comment]
@kenman345 looks like the issue with reminders not working on PR is a permission issue:

https://github.com/probot/reminders/issues/38

could you look into it? I'd like to set a reminder for this issue.

**Comment by kenman345** [comment]
best I might be able to do is make the bot able to merge something on a date but it seems like a lot of effort for nothing. I usually check each week before the weekly builds what we have open so i will notice this one

**Comment by EchterAgo** [comment]
The reminders bot, which we have already installed and works on issues, should work on PRs if the permissions are set right. Are you sure it has access to pull requests?

**Comment by kenman345** [comment]
@EchterAgo can you take a look at what needs to be resolved to merge this?

**Comment by EchterAgo** [comment]
Rebased

**Comment by kenman345** [comment]
You can merge it whenever

**Pull request merged**
