### PR TITLE
Batch update 2018-04-27

### PR DESCRIPTION
**Pull request by EchterAgo**

### CODE REVIEW

**Comment by kenman345** [comment]
Paul W of BCf said he found these had closed:
https://named.trade
https://tekkfolio.com

Mind taking a look and adding to this PR? I think they’re both domain registrars

**Comment by kenman345** [comment]
Lol you said tekfolio but you removed Named....good thing both need to go

**Comment by EchterAgo** [comment]
Hmm, one commit removing named, one tekkfolio. although i forgot to include the yaml changes in the tekkfolio commit.

**Comment by kenman345** [comment]
closes #893  BTW.....you forgot to mention it so lets remember to close it next time

**Pull request merged**
