### PR TITLE
Add 'Cardbit' to the 'Cryptoservices' category

### PR DESCRIPTION
**Pull request by accept-bitcoin-cash**
Requesting to add 'Cardbit' to the 'Cryptocurrency' category. 

Details follow: 
```yml 
- name: Cardbit
  url: http://www.cardbit.io
  img: Cardbit.png
  bch: false
  btc: true
  othercrypto: true
  email_address: ok@cardbit.io
```

Resources for adding this merchant:
[Link to Cardbit](http://www.cardbit.io)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.cardbit.io)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.cardbit.io)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.cardbit.io)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

### CODE REVIEW

**Comment by accept-bitcoin-cash** [comment]
Processed

**Comment by kenman345** [comment]
/abcbot image Cardbit.png https://www.cardbit.io/site/assets/img/brand/favicon.ico

**Comment by accept-bitcoin-cash** [comment]
Unable to add Cardbit.png to img/cryptoservices.

**Comment by kenman345** [comment]
not sure if it could handle .ico but it was worth a try

**Pull request closed without merging**
