### PR TITLE
changing back

### PR DESCRIPTION
**Pull request by kenman345**
didnt help the dead url issue on travis. putting back to main level site

### CODE REVIEW

**Comment by EchterAgo** [comment]
The cointiger link seems to work fine for me. The reason I asked about it is because I take care to remove URLs that go to a specific language. Like https://some.site/en/index.html, there I would put https://some.site/ to make language specific redirects take you to the right site.

**Comment by kenman345** [comment]
no I agree, I wanted to get rid of the error on the link validations and thought that would fix it but it did not, so changing it back

**Comment by EchterAgo** [comment]
Oh, I wasn't aware there was an error. I guess I should get a Linux build environment set up sometime so that I can run full rake.

**Comment by kenman345** [comment]
I still havent done that either. I run in Windows and can run everything but the HTML proofer stuff. I use travis output for those.

**Comment by kenman345** [comment]
Though I am getting a rPi 3B+ setup tonight to run docker so I can play around with some stuff. I wanna see about making use of HTTP2 Server Push stuff but havent had any other way to test changes for that.

**Comment by EchterAgo** [comment]
How can I see those without my tests failing?

**Comment by kenman345** [comment]
the second job on travis-ci is the ones that are allowed to fail. Thats the one that validates the external links

**Comment by kenman345** [comment]
https://travis-ci.org/acceptbitcoincash/acceptbitcoincash/jobs/396904430

We only have that second job on PRs though. it takes time and why bother with every push when its allowed to fail anyways.

**Pull request merged**
