### PR TITLE
Add 'Joey Trend' to the 'Domains' category

### PR DESCRIPTION
**Pull request by accept-bitcoin-cash**
Requesting to add 'Joey Trend' to the 'Domains' category. 

Details follow: 
```yml 
- name: Joey Trend
  url: https://joeytrend.com/2019/10/02/why-i-like-bitcoin-cash/
  img: JoeyTrend.png
  bch: true
  btc: true
  othercrypto: true
  twitter: joeytrend
  email_address: joeytrend@aol.com
  country: US
  city: Atlanta
```

Resources for adding this merchant:
[Link to Joey Trend](https://joeytrend.com/2019/10/02/why-i-like-bitcoin-cash/)
Check their Twitter Page: [twitter.com/joeytrend](https://twitter.com/joeytrend)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/joeytrend.com/2019/10/02/why-i-like-bitcoin-cash/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/joeytrend.com/2019/10/02/why-i-like-bitcoin-cash/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/joeytrend.com/2019/10/02/why-i-like-bitcoin-cash/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

### CODE REVIEW

**Comment by georgengelmann** [comment]
I guess the website is okay, but Joey Trend is a notorious memo.cash spammer

**Comment by kenman345** [comment]
Would you say that the site is legitimate or not? I am okay with the owner being his own person as long as it’s a site we expect to operate properly and provide the advertised services in return for payment and not run off with your money or target you with scams after signing up

**Comment by kenman345** [comment]
I am sorry, I never looked at this before. This doesnt seem to be a business, more like a blog. I am okay to list this in entertainment if they accepted donations but I could not find any link for that so I am closing this.

**Comment by georgengelmann** [comment]
Domain was first seen by Netcraft: August 2018 - Risk rating 1/10 (0 lowest risk, 10 highest)

Google Safe Browsing: Clean (Current Verdict)

The website is looking clean, but it's just articles about Bitcoin Cash - Domains category is for selling Domain names, not for blogs or personal promotion ...

**Comment by georgengelmann** [comment]
I would not list it anywhere to be honest, the owner is spamming memo.cash and it looks like he's trying anything for links instead of producing better content (natural visitor increase happen if you're just writing good articles, you know? some promotion is okay, but thousands of memos are not)

**Pull request closed without merging**
