### PR TITLE
why not add a sitemap for better SEO?

### PR DESCRIPTION
**Pull request by kenman345**

### CODE REVIEW

**Comment by kenman345** [comment]
I was thinking we wait to merge this until tomorrow when I can add in a HTML page that users can click through as well. Very plain and simple. Akin to https://varvy.com/sitemap.html

**Comment by kenman345** [comment]
This should not be merged until we make the UI a little better. I did what I could during my lunch break but it definitely needs a little more of a look over.

**Comment by kenman345** [comment]
I merged this since we had some approval, and we dont need to mention the `/sitemap` url endpoint until we are ready. 

@t0p0lin0 please check out beta page if you can to see how it currently is. Would like it to be a little cleaner before we mention it anywhere.

**Comment by t0p0lin0** [comment]
I certainly will do at first chance @kenman345.

**Pull request merged**
