### PR TITLE
Add 'The Scot Hotel' to the 'Accommodation' category

### PR DESCRIPTION
**Pull request by accept-bitcoin-cash**
Requesting to add 'The Scot Hotel' to the 'Accommodation' category. 

Details follow: 
```yml 
- name: The Scot Hotel
  url: https://thescotoban.com/
  img: TheScotHotel.png
  bch: true
  btc: false
  othercrypto: false
  email_address: info@thescotoban.com
  region: eu
  country: GB
  city: Oban
  exceptions:
    text: "Can reserve room with credit card info and pay with BCH at reception."
```

Resources for adding this merchant:
[Link to The Scot Hotel](https://thescotoban.com/)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/thescotoban.com/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/thescotoban.com/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/thescotoban.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

### CODE REVIEW

**Comment by kenman345** [comment]
/abcbot image TheScotHotel.png https://scontent-lga3-1.xx.fbcdn.net/v/t1.0-9/46506299_2216935671916926_2665754306476507136_n.jpg?_nc_cat=103&_nc_oc=AQl9MTA-r7QSWzsUHLT6Vr5NEEoOo_4EruQ73tb6ifoMIWLZNz4A5DIm88ET6k8p3oQ&_nc_ht=scontent-lga3-1.xx&oh=fc9c962f568958c55c5b823a89196808&oe=5E26AD30

**Comment by accept-bitcoin-cash** [comment]
Unable to add TheScotHotel.png to img/accommodation.

**Comment by kenman345** [comment]
/absbot image TheSotHotel.png https://i.imgur.com/2Z5aByH.jpg

**Comment by kenman345** [comment]
/abcbot image TheScotHotel.png https://i.imgur.com/2Z5aByH.jpg

**Comment by accept-bitcoin-cash** [comment]
Unable to add TheScotHotel.png to img/accommodation.

**Comment by kenman345** [comment]
/abcbot image TheScotHotel.png https://i.imgur.com/2Z5aByH.jpg?1

**Comment by accept-bitcoin-cash** [comment]
Saved TheScotHotel.png to img/accommodation folder.

**Pull request merged**
