### PR TITLE
Add EARTH to IoT section.

### PR DESCRIPTION
**Pull request by cgcardona**
Adding EARTH to the IoT section. Thanks for a great site!

### CODE REVIEW

**Comment by deadr0ck** [comment]
You're welcome, glad to add EARTH - but do you have a 32x32 icon we can use?

Thanks

**Comment by cgcardona** [comment]
Something other than this? https://github.com/cgcardona/acceptbitcoincash/blob/bfefa23a1610ae9441347e18561a35f0cd5253ac/img/iot/earth.png

**Comment by cgcardona** [comment]
I just noticed that that icon in the PR looks like it's 34 x 34. But I made it 32 x 32 and ran it through OptiPNG before committing.

**Comment by zquestz** [comment]
So just a black circle image?

**Pull request merged**
