### PR TITLE
Add 'Soulobjects' to the 'retailer' category

### PR DESCRIPTION
**Pull request by accept-bitcoin-cash**
Requesting to add 'Soulobjects' to the 'retailer' category. 

Details follow: 
```yml 
- name: Soulobjects
      url: https://soulobjects.de/
      img: 
      facebook: soulobjects
      bch: Yes
      btc: Yes
      othercrypto: No
      exceptions: 
        text: "over BitPay"
```

Resources for adding this merchant:
Logo Provided:
Soulobjects
[Link to Soulobjects](https://soulobjects.de/)
If needed, try the facebook handles profile image: [fb.com/soulobjects](https://fb.com/soulobjects)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/soulobjects.de/](https://www.alexa.com/siteinfo/soulobjects.de/)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/soulobjects.de/](https://www.scamadviser.com/check-website/soulobjects.de/)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/soulobjects.de/](https://www.trustpilot.com/review/soulobjects.de/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

### CODE REVIEW

**Comment by kenman345** [comment]
@EchterAgo looks a bit thrown together, note the bottom left of the main page has an error. What are your thoughts?

**Comment by EchterAgo** [comment]
Them using BitPay is already a good indication that they are a proper company. I also checked the Handelsregister and they have a valid registration. Also they seem to be doing everything to comply with all German regulations, even their terms of service are not copied. The domain is at least 4 years old and I've found good feedback for the company. Looks very legitimate.

**Comment by EchterAgo** [comment]
Photo from Prenzlauer Allee 24 in Berlin:

image

So yea, we should definitely list them.

**Comment by kenman345** [comment]
so approve it and merge it, awesome work

**Comment by EchterAgo** [comment]
I still want to check if the listing is right.

**Pull request merged**
