### PR TITLE
Add 'Lingo.cash' to the 'Services' category

### PR DESCRIPTION
**Pull request by accept-bitcoin-cash**
Requesting to add 'Lingo.cash' to the 'Translations' category. 

Details follow: 
```yml 
- name: Lingo.cash
  url: https://www.lingo.cash/
  img: Lingocash.png
  bch: true
  btc: false
  othercrypto: false
  twitter: lingocash1
  facebook: lingocash1
  email_address: translations@lingo.cash
```

Resources for adding this merchant:
Logo Provided:
ProvidedLogoURL
Twitter Profile Image (48x48):
TwitterProfileImageURL
Facebook Profile Image:
FacebookProfileImageURL
[Link to Lingo.cash](https://www.lingo.cash/)
Check their Twitter Page: [twitter.com/lingocash1](https://twitter.com/lingocash1)
Check their Facebook Page: [fb.com/lingocash1](https://fb.com/lingocash1)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.lingo.cash/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.lingo.cash/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.lingo.cash/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by Twitter user [lingocash1](https://twitter.com/lingocash1/), be sure to send out a tweet when this request has been added.

### CODE REVIEW

**Comment by accept-bitcoin-cash** [comment]
Processed and ready to be evaluated.

**Comment by accept-bitcoin-cash** [comment]
To use the bot, comment with a valid command one any issue or PR that has a section/[category] label applied to it. Instructions on sentence structure and commands are listed below.

Commands should be formatted in the following manner:
`/ABCBot [action] [arg1] [arg2]`

Available Commands/Arguments:
```
/ABCBot image [image_name] [image_url]
  -- Adds image to PR
/ABCBot process
/ABCBot process [category]
  -- Opens PR for listing.
  -- When used with optional parameter, adds in the category label to listing.
/ABCBot toggle [listing name: value] [btc|bch|bsv|othercrypto] ...
  -- Opens PR for listing to be updated with toggled values for cryptocurrency tracking.
  -- This will accept multiple final parameters as long as they are of the right types.
/ABCBot remove [listing name: value]
  -- Opens PR for listing to be removed.
/ABCBot help
```

**Comment by EchterAgo** [comment]
/ABCBot image Lingocash.png https://camo.githubusercontent.com/419c69d3c4b258e4f8a5b17417b1ef044121e600/68747470733a2f2f7062732e7477696d672e636f6d2f70726f66696c655f696d616765732f313039353737393533333539353236323937362f77694471724650585f6e6f726d616c2e706e67

**Comment by accept-bitcoin-cash** [comment]
Saved Lingocash.png to img/services folder.

**Comment by EchterAgo** [comment]
I've got back a nice Russian translation of my software from this service. 👍

**Pull request merged**
