### PR TITLE
Add 'nordVPN' to the 'Security' category

### PR DESCRIPTION
**Pull request by accept-bitcoin-cash**
Requesting to add 'nordVPN' to the 'Security' category. 

Details follow: 
```yml 
- name: nordVPN
  url: https://nordvpn.com
  img: nordVPN.png
  bch: true
  btc: true
  othercrypto: true
  twitter: nordvpn
  facebook: nordvpn
  email_address: support@nordvpn.com
  exceptions:
    text: "payments through Coinpayment"
```

Resources for adding this merchant:
[Link to nordVPN](https://nordvpn.com)
Check their Twitter Page: [twitter.com/nordvpn](https://twitter.com/nordvpn)
Check their Facebook Page: [fb.com/nordvpn](https://fb.com/nordvpn)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/nordvpn.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/nordvpn.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/nordvpn.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

### CODE REVIEW

**Comment by kenman345** [comment]
I’m gonna approve this one I put back the keyword and remove the exception.

**Comment by EchterAgo** [comment]
This is wrong, they still do not support Bitcoin Cash.

**Comment by kenman345** [comment]
Well crap. That blows

**Comment by EchterAgo** [comment]
Yea, I was already hoping I could finally renew my subscription with them
which I paid before the BCH split. Been trying forever to get them to
accept it, but it seems their reasons are political and they are lying
about the reasons. Multiple people on reddit said the same. They used to
use Bitpay but right before bitpay enabled BCH they switched to coin
payments and haven't enabled BCH there. I actually checked this a few days
ago and was surprised to see this here, but I tried again and it is still
not enabled. Back in December 2017 I actually got an email from their CFO
suggesting they will enable it, I wonder what changed.

**Comment by EchterAgo** [comment]
Just checked it again, still no Bitcoin Cash. Closing.

**Pull request closed without merging**
