### PR TITLE
Add P2P crypto marketplace findbits.com

### PR DESCRIPTION
**Pull request by chanar**

### CODE REVIEW

**Comment by kenman345** [comment]
this is only a cryptoservice, not a cryptoexchange.

Please remove the updates to the cryptoexchange.yml and the added png so we only are adding this listing to the crypto services section

**Comment by kenman345** [comment]
also appears you need to  fix the ordering

**Comment by chanar** [comment]
Thanks, on it.

**Comment by kenman345** [comment]
the error logs contain the ordering information you need.

**Comment by chanar** [comment]
I have fixed the problems. No new line at the end of file is OK?

**Comment by kenman345** [comment]
looks good, waiting on our Continuous Integration to complete before adding a passing review and merging.

**Comment by chanar** [comment]
Great, thank you @kenman345

**Pull request merged**
