### PR TITLE
Added Futon Beds From Japan

### PR DESCRIPTION
**Pull request by hegjon**
They accept Bitcoin and Bitcoin Cash by selecting manual payment in the checkout.

### CODE REVIEW

**Comment by hegjon** [comment]
I can redo the PR, is it best with the URL to the icon or to check it into git?

**Comment by kenman345** [comment]
you can just push a new commit to the PR.

"Add more commits by pushing to the master branch on hegjon/acceptbitcoincash."

**Comment by hegjon** [comment]
Second try now :)

**Comment by kenman345** [comment]
Please remove the exception, its spaced wrong and doesnt meet the requirements of why its to be used.

Otherwise this looks good and will be able to be merged once thats updated.

**Comment by kenman345** [comment]
favicon is 32x32?

**Comment by kenman345** [comment]
looks to be 20x20 which also fails. Generally I just use imgur to crop the image and resize it, then add to my local copy of the repo and commit it. I recommend doing that with hte original image.

Sorry about all the issues, just made some changes while you were doing this that failed that initial build.

**Comment by hegjon** [comment]
Yes, looks like the favicon is 20x20, will scale it to 32x32

**Comment by kenman345** [comment]
Yes, please scale down the original image. the favicon will be low quality and a poor representation of the merchant when we have better options.

**Comment by hegjon** [comment]
I have replaced the icon with version that I modified with GIMP from the original logo, exception is also removed

**Comment by kenman345** [comment]
looks good. Would prefer for consistency that we had the twitter and facebook handles but since they accept BCH its not a blocker. Once Travis completes its build test I will merge it in.

**Comment by hegjon** [comment]
I can add twitter and facebook

**Comment by kenman345** [comment]
please dont, I am merging this PR

**Pull request merged**
