### PR TITLE
Batch update

### LINKED ISSUE #1431: Handle Bitcoin SV listings
Our options are

1. Remove them
2. Flip them to `othercrypto`
3. Add `bsv` status

Personally I prefer option 2. Here is a list of services I know will use BSV, haven't checked that all of them are listed:

- handcash
- moneybutton
- yours
- cryptografitti
- cryptonize.it
- https://bitek.co/

### PR DESCRIPTION
**Pull request by EchterAgo**
closes #1431

### CODE REVIEW

**Comment by kenman345** [comment]
Thanks for moving those. Since the bot is JS based I’ll just have it check if doc has a value and get the match index for “http”. If I don’t find it at the first position then I’ll move that to the exception text tag instead

**Comment by EchterAgo** [comment]
Would it be OK to already flip `cryptonize.it` and `yours.org` to BSV? It is pretty clear they will be going with SV and we could then close #1431

**Comment by kenman345** [comment]
Go for it! If you think their is no potential it might support both

**Comment by EchterAgo** [comment]
@kenman345 review please

**Pull request merged**
