### PR TITLE
Add 'The Gamer's Hut' to the 'Retail' category

### PR DESCRIPTION
**Pull request by accept-bitcoin-cash**
Requesting to add 'The Gamer's Hut' to the 'Computers, PC Gaming & Accessories' category. 

Details follow: 
```yml 
- name: The Gamer's Hut
  url: https://shopgamerhut.com
  img: TheGamersHut.png
  bch: true
  btc: true
  othercrypto: true
  email_address: sales@shopgamerhut.com
  exceptions:
    text: "Select payment by Coinbase Commerce option at checkout."
```

Resources for adding this merchant:
Logo Provided:
ProvidedLogoURL
[Link to The Gamer's Hut](https://shopgamerhut.com)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/shopgamerhut.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/shopgamerhut.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/shopgamerhut.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

### CODE REVIEW

**Comment by accept-bitcoin-cash** [comment]
Processed

**Comment by accept-bitcoin-cash** [comment]
To use the bot, comment with a valid command one any issue or PR that has a section/[category] label applied to it. Instructions on sentence structure and commands are listed below.

Commands should be formatted in the following manner:
`/ABCBot [action] [arg1] [arg2]`

Available Commands/Arguments:
```
/ABCBot image [image_name] [image_url]
  -- Adds image to PR
/ABCBot process
/ABCBot process [category]
  -- Opens PR for listing.
  -- When used with optional parameter, adds in the category label to listing.
/ABCBot toggle [listing name: value] [btc|bch|bsv|othercrypto] ...
  -- Opens PR for listing to be updated with toggled values for cryptocurrency tracking.
  -- This will accept multiple final parameters as long as they are of the right types.
/ABCBot remove [listing name: value]
  -- Opens PR for listing to be removed.
/ABCBot help
```

**Comment by EchterAgo** [comment]
/ABCBot image TheGamersHut.png https://i.imgur.com/Hug999e.png

**Comment by accept-bitcoin-cash** [comment]
Saved TheGamersHut.png to img/retail folder.

**Pull request merged**
