### PR TITLE
Batch update

### PR DESCRIPTION
**Pull request by EchterAgo**

### CODE REVIEW

**Comment by zquestz** [comment]
@kenman345 did you want to review? I looked and it seemed right. =)

**Comment by kenman345** [comment]
Just push whatever you want. I’m a little preoccupied and you usually just
change kubernetes stuff so if something else is wrong with the build it’s
still worth pushing through and making sure I go in and fix the rest of the
build

**Comment by zquestz** [comment]
Has a few minor conflicts because of the other large PR that merged. =)

**Comment by EchterAgo** [comment]
I'll fix it.

**Comment by EchterAgo** [comment]
Hmm, anyone know how to fix the problem?

**Comment by zquestz** [comment]
Fix is in my PR -> https://github.com/acceptbitcoincash/acceptbitcoincash/pull/1802

**Comment by zquestz** [comment]
https://github.com/acceptbitcoincash/acceptbitcoincash/pull/1802/commits/e2f075a3c9c0df98d249610a37707fbcf16d7d4c

**Comment by zquestz** [comment]
If you rebase this will go green, then I can +1 and merge.

**Comment by EchterAgo** [comment]
Rebased on #1803

**Comment by EchterAgo** [comment]
Actually, I'll close #1803, doesn't make sense to have it separate.

**Comment by EchterAgo** [comment]
This seems to be stuck.

**Comment by zquestz** [comment]
We need @kenman345 to merge it. =\

**Pull request merged**
