### PR TITLE
Batch update

### LINKED ISSUE #1264: Add a new section for sites listing where you can spend Bitcoin Cash?
As said in #1262. There are a few already:

- [Marco Coino](https://marcocoino.bitcoin.com/)
- [Bitcoin People Online](https://bitcoinpeople.online/) (#1170)
- [The Real Bitcoin Club](https://map.therealbitcoin.club/) (#1224)
- [greenpages.cash](https://greenpages.cash/)

I think it would be a good idea to create a new category for these and link them here.

### PR DESCRIPTION
**Pull request by EchterAgo**
closes #1264

### CODE REVIEW

**Comment by EchterAgo** [comment]
@kenman345 ready for review

**Comment by EchterAgo** [comment]
Did a bit of cleanup and removed a lot of websites that have been down for a long time.

**Comment by EchterAgo** [comment]
We are still far over 1000 listings :)

**Comment by kenman345** [comment]
can you update beardfrindly in the health section? I looked and it appears they now use coinbase commerce and accept BTC, BCH and alts

**Comment by EchterAgo** [comment]
Ah, that is great. I'm on my phone now though, but I'll do it soon.

**Comment by kenman345** [comment]
yea, I think some time has passed and some of the places that stopped due to the service just neeeding to be updated might have fixed it. we should double check some of them that all kinda stopped around that same time (aka last may fork)

**Comment by EchterAgo** [comment]
Yea, I checked the coinbase merchant tools vendors multiple times and also sent them emails. I still have them on my list for another check soon

**Comment by kenman345** [comment]
69 commits in this one. NICE....

gonna squash it though, thats a bit up there.

**Comment by kenman345** [comment]
meant squash on merge

**Comment by EchterAgo** [comment]
I changed beardfriendly. I'd prefer no squashing, makes revert easier if a change was wrong.

**Comment by kenman345** [comment]
okay, i wont squash

**Comment by EchterAgo** [comment]
I also want to recheck the vendors that have been down again in a few months.

**Comment by EchterAgo** [comment]
I think that is the first update that made the counts go negative. But still better than listing many broken sites.

**Comment by kenman345** [comment]
I really wish I had the time to write up something that would give us the net between merges and/or releases. One day I might get to it

**Comment by EchterAgo** [comment]
The merchant monday thread already shows how many were added. I'm not sure if it shows negative numbers.

**Comment by kenman345** [comment]
my thoughts on a script were maybe make it a rake task, and then have it pull from the production site the json and figure out the comparisons, but getting it to do that is effort i dont have the time for now. because then it would at least be in the logs, maybe even something to throw into a json.

**Pull request merged**
