### PR TITLE
Add The Keyois Capsule

### PR DESCRIPTION
**Pull request by daftspunk**
> can you add the nutty professor: 
> https://www.reddit.com/r/btc/comments/78g0m6/bitcoin_cash_works_in_bavaria/dotmqer/

### CODE REVIEW

**Comment by kenman345** [comment]
doc tag wrong @rawb0t

**Comment by kenman345** [comment]
nevermind, doc tag unnecessary. but also this is a wallet

**Comment by rawb0t** [comment]
is it really a wallet though? you do bring up a good point that maybe security isn't the right category but it's cold storage -- you've gotta break the device to retrieve the funds

**Comment by kenman345** [comment]
break it? really? 

found this: 

> After you order and receive your package you may wonder how to open it. After taking out the unique sealed container just tap it with a hammer once or twice to reveal the goods inside.

I kind of love it more now....

**Comment by kenman345** [comment]
@daftspunk will you move that change to wallet.yml and remove it from security.yml and dont need the doc tag/link. I'll push it through right after

**Comment by rawb0t** [comment]
is a piggy bank a wallet?

**Comment by kenman345** [comment]
looks at piggy bank....looks back at computer....

YES

**Comment by t0p0lin0** [comment]
The category can always be changed later via PR if necessary. Side point - cool device!

**Pull request merged**
