### PR TITLE
Fix extra indent for Boxcryptor

### PR DESCRIPTION
**Pull request by t0p0lin0**

### CODE REVIEW

**Comment by kenman345** [comment]
already a part of my PR thats pending

**Comment by kenman345** [comment]
#473   ....last commit

**Comment by t0p0lin0** [comment]
My apologies, hadn't noticed it!

**Comment by kenman345** [comment]
yea, remember i was testing travis....lol

**Comment by t0p0lin0** [comment]
I should have excluded this change in that 'image fallback' PR @joshmcintyre, so I will close this PR now.

**Pull request closed without merging**
