### PR TITLE
Add 'Stake' to the 'Gambling' category

### PR DESCRIPTION
**Pull request by accept-bitcoin-cash**
Requesting to add 'Stake' to the 'Gambling' category. 

Details follow: 
```yml 
- name: Stake
  url: https://stake.com/
  img: Stake.png
  bch: true
  btc: true
  othercrypto: true
  twitter: stake
  facebook: stakecasino
```

Resources for adding this merchant:
Twitter Profile Image (48x48):
TwitterProfileImageURL
[Link to Stake](https://stake.com/)
If needed, try the twitter handles profile image: [twitter.com/stake](https://twitter.com/stake)
If needed, try the facebook handles profile image: [fb.com/stakecasino](https://fb.com/stakecasino)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/stake.com/](https://www.alexa.com/siteinfo/stake.com/)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/stake.com/](https://www.scamadviser.com/check-website/stake.com/)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/stake.com/](https://www.trustpilot.com/review/stake.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

### CODE REVIEW

**Comment by kenman345** [comment]
Honestly, Its nice that this replaces the listing and I dont think we really need the doc link anymore. Its been a long time that they've accepted crypto so why waste the bytes on the webpage to render?

**Comment by kenman345** [comment]
going to dismiss this request. Noticed that the image name didnt match the before. which is not a good thing since it will leave one orphaned. I shall have to figure out a way of identifying that situation. Going to downcase everything from now on.

**Comment by accept-bitcoin-cash** [comment]
To use the bot, comment with a valid command one any issue or PR that has a section/[category] label applied to it. Instructions on sentence structure and commands are listed below.

Commands should be formatted in the following manner:
`/ABCBot [action] [arg1] [arg2]`

Available Commands/Arguments:
```/ABCBot image [image_name] [image_url]
  -- Adds image to PR
/ABCBot remove [listing name: value]
  -- Opens PR for listing to be removed.
/ABCBot toggle [listing name: value] [btc|bch|othercrypto] [btc|bch|othercrypto] [btc|bch|othercrypto]
  -- Opens PR for listing to be updated with toggled values for cryptocurrency tracking. 
  -- This will accept multiple final parameters as long as they are of the right types. 
/ABCBot process
/ABCBot process [category]
  -- Opens PR for listing.
  -- When used with optional parameter, adds in the category label to listing.
/ABCBot help
 ```

**Comment by kenman345** [comment]
/ABCBot image stake.png https://pbs.twimg.com/profile_images/1047309112550125568/BUlpYyAE_normal.jpg

**Comment by accept-bitcoin-cash** [comment]
Saved stake.png to gambling folder.

**Pull request closed without merging**
