### PR TITLE
Batch update

### PR DESCRIPTION
**Pull request by EchterAgo**

### CODE REVIEW

**Comment by EchterAgo** [comment]
Done for now, review please

**Comment by kenman345** [comment]
hey, arent Coins.ph and coins.co.th the same company?

**Comment by kenman345** [comment]
it is, but no announcement fro them yet. I believe their systems are the same, so lets remember to update/verify both once coins.ph has implemented BCH

**Comment by EchterAgo** [comment]
They kind of are, at least they share login details and you even need to use the coins.ph app to use the service. Despite this, customer support made a it a point to me before that they are not the same company when I had problems with services on coins.ph with an account registered on coins.co.th.

**Comment by EchterAgo** [comment]
I will definitely be updating them as soon as they support it, and I do believe coins.co.th will add it as well.

**Pull request merged**
