### PR TITLE
Adding mining section

### PR DESCRIPTION
**Pull request by deadr0ck**
Added mining.yml with BCC pools:

Antpool, BitClub Network, Bitcoin.com, BTC.com, BTC.TOP, Suprnova and ViaBTC

### CODE REVIEW

**Comment by deadr0ck** [comment]
Still needs a logo for the section.

**Comment by deadr0ck** [comment]
Just moving it from this section to Mining

**Comment by rawb0t** [comment]
oh. whoops. didnt notice the filename.

**Comment by t0p0lin0** [comment]
Nice work @deadr0ck -- All looks good, but yes, the icon is still needed for the category. This is the set that is used: https://semantic-ui.com/elements/icon.html -- though I couldn't quickly find a suitable icon for "mining" (there are no pick axes).

My suggestions might be (in no particular order, and use CTRL+F to find these):

- server
- microchip
- cubes (i.e. blockchain)

Pretty sure none of the above are used to represent other categories, but it'd be good to make sure.

**Comment by kenman345** [comment]
I am actually a bit preferable to using 'diamond' or 'puzzle' for the mining section

**Comment by kenman345** [comment]
Even though I suggested others, of the ones @t0p0lin0 suggested, I prefer 'server' the most. please do not use the cubes, I see it used too often in the wrong setting, I cringe whenever I see it

**Comment by t0p0lin0** [comment]
Added the `server` icon per the latest commit. Please update your review @kenman345 @rawb0t @deadr0ck

**Pull request merged**
