### PR TITLE
Batch update 2018-05-20

### PR DESCRIPTION
**Pull request by EchterAgo**
* Removed one dead listing.
* Updated language and location tags for listings.
* Add Twitter and Facebook links to one listing.
* Update opwaarderen.nl, they no longer accept BCH/BTC. Was added recently in #768

### CODE REVIEW

**Comment by EchterAgo** [comment]
Ready for review

**Comment by EchterAgo** [comment]
Actually, I will go through the open issues first.

**Comment by EchterAgo** [comment]
Ready for review now

**Comment by EchterAgo** [comment]
I just checked, it is not live yet. They say this in their blog:

> The update is being tested to ensure a smooth experience with a target live date by the end of May. In addition, once Bitcoin Cash goes live, users who missed the post-fork withdrawal period will be happy to see their balance restored.

**Comment by EchterAgo** [comment]
Oh, I'll point the status at the blog.

**Comment by EchterAgo** [comment]
Done

**Comment by EchterAgo** [comment]
BTW, the "moneybutton.com" name was directly given to me by Ryan. They might decide to change this in the future.

**Comment by kenman345** [comment]
Merge it then

**Pull request merged**
