### PR TITLE
Add CBD supply shop

### PR DESCRIPTION
**Pull request by EchterAgo**
Not sure if this is the right category

### CODE REVIEW

**Comment by hegjon** [comment]
I think alt. medicine would be a better category

**Comment by EchterAgo** [comment]
Yea, that's what I've been thinking too. I'm not sure though. That have a
lot of vape stuff.

**Comment by kenman345** [comment]
I’m not opposed to dual listing for these.

**Comment by EchterAgo** [comment]
What is the process for dual listing? Just copy and paste?

**Comment by kenman345** [comment]
Add the listing fresh to the second section with a second copy of the logo.

**Pull request merged**
