### PR TITLE
Add 'Crispy Barbers' to the 'Services' category

### PR DESCRIPTION
**Pull request by accept-bitcoin-cash**
Requesting to add 'Crispy Barbers' to the 'Services' category. 

Details follow: 
```yml 
- name: Crispy Barbers
  url: https://www.instagram.com/crispybarbers/
  img: CrispyBarbers.png
  bch: true
  btc: true
  othercrypto: true
  facebook: crispybarbers
  email_address: crispybarbers@gmail.com
  region: as
  country: TW
  city: Tainan city
```

Resources for adding this merchant:
[Link to Crispy Barbers](https://www.instagram.com/crispybarbers/)
Check their Facebook Page: [fb.com/crispybarbers](https://fb.com/crispybarbers)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.instagram.com/crispybarbers/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.instagram.com/crispybarbers/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.instagram.com/crispybarbers/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

### CODE REVIEW

**Comment by kenman345** [comment]
I'm not sure about listing it, if we do, it should at least be the facebook site since that at least contains the location information about the retailer.

**Comment by kenman345** [comment]
And Tainan city should just be Tainan

**Comment by EchterAgo** [comment]
Sent them a message to confirm whether they accept cryptocurrencies.

**Comment by EchterAgo** [comment]
The official name is actually "Tainan City"

**Comment by EchterAgo** [comment]
They confirmed to me that they do accept BCH.

**Pull request merged**
