### PR TITLE
Add 'beit-limited.com' to the 'Health' category

### PR DESCRIPTION
**Pull request by accept-bitcoin-cash**
Requesting to add 'beit-limited.com' to the 'Beauty Product' category. 

Details follow: 
```yml 
- name: beit-limited.com
  url: https://www.beit-limited.com/
  img: beitlimitedcom.png
  bch: true
  btc: false
  othercrypto: true
  region: eu
  country: GB
```

Resources for adding this merchant:
[Link to beit-limited.com](https://www.beit-limited.com/)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.beit-limited.com/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.beit-limited.com/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.beit-limited.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

### CODE REVIEW

**Comment by accept-bitcoin-cash** [comment]
Processed

**Comment by EchterAgo** [comment]
uses coinpayments.net

**Comment by EchterAgo** [comment]
/ABCBot image beitlimitedcom.png https://i.imgur.com/a3IHQjL.png

**Comment by accept-bitcoin-cash** [comment]
Saved beitlimitedcom.png to img/health folder.

**Pull request merged**
