### PR TITLE
[Chore] Update kube deployment to reflect accurate memory requirements

### PR DESCRIPTION
**Pull request by zquestz**
Was monitoring memory usage across the pods in my cluster and realized 16Mi is plenty.

### CODE REVIEW

**Comment by zquestz** [comment]
Fixed the issue the tests were complaining about. They need to be rerun. =)

**Comment by zquestz** [comment]
New build already passed. https://travis-ci.org/github/acceptbitcoincash/acceptbitcoincash/builds/667534128

**Comment by zquestz** [comment]
@EchterAgo you should approve this so I can fix the build =)

**Comment by zquestz** [comment]
Hmm, how do I get this to pickup the rerun tests? They are green but the status didn't update and I can't merge...

**Comment by kenman345** [comment]
Hm, I’ll look into it tonight

**Pull request merged**
