### PR TITLE
Add 'KJC Gold Silver Bullion' to the 'Precious Metals & Jewelry' category

### PR DESCRIPTION
**Pull request by accept-bitcoin-cash**
Requesting to add 'KJC Gold Silver Bullion' to the 'Precious Metals & Jewelry' category. 

Details follow: 
```yml 
- name: KJC Gold Silver Bullion
  url: https://www.kjc-gold-silver-bullion.com.au/
  img: KJCGoldSilverBullion.png
  bch: true
  btc: true
  othercrypto: false
  region: oc
  country: AU
  city: Sydney
  doc: https://www.kjc-gold-silver-bullion.com.au/buy-payment-option/
```

Resources for adding this merchant:
Logo Provided:
ProvidedLogoURL
[Link to KJC Gold Silver Bullion](https://www.kjc-gold-silver-bullion.com.au/)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.kjc-gold-silver-bullion.com.au/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.kjc-gold-silver-bullion.com.au/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.kjc-gold-silver-bullion.com.au/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by @zveda

### CODE REVIEW

**Comment by EchterAgo** [comment]
Yea, I'll add the image. Was still verifying the site.

**Comment by EchterAgo** [comment]
@kenman345 review please

**Comment by kenman345** [comment]
hmm....seems legit but maybe @zveda can chime in a little more background on this site? Its a little more crypto focused than any of the other listings.

**Comment by EchterAgo** [comment]
The site is legit and I already confirmed all the details. I just can't merge without review.

**Comment by zveda** [comment]
I've been using this precious metals dealer for years. They have a physical location in Sydney CBD as well. Much lower prices than major bullion dealers in Sydney like ABC Bullion.

Also they apparently have foreign clients as well - I didn't put that into the form.

**Pull request merged**
