### PR TITLE
Add 'X CryptoMarket' to the 'Online Marketplace - P2P' category

### PR DESCRIPTION
**Pull request by accept-bitcoin-cash**
Requesting to add 'X CryptoMarket' to the 'Online Marketplace - P2P' category. 

Details follow: 
```yml 
- name: X CryptoMarket
  url: https://xcryptomarket.com
  img: XCryptoMarket.png 
  bch: true
  btc: true
  othercrypto: true
```

Resources for adding this merchant:
[Link to X CryptoMarket](https://xcryptomarket.com)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/xcryptomarket.com](https://www.alexa.com/siteinfo/xcryptomarket.com)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/xcryptomarket.com](https://www.scamadviser.com/check-website/xcryptomarket.com)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/xcryptomarket.com](https://www.trustpilot.com/review/xcryptomarket.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

### CODE REVIEW

**Comment by accept-bitcoin-cash** [comment]
Processing

**Comment by kenman345** [comment]
Every social media link in the footer links to itself...

**Comment by EchterAgo** [comment]
The social media links is a common problem. Not quite sure why.

**Comment by EchterAgo** [comment]
I'm really not sure about this, but I'd say reject because the TOS is

> Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.

https://xcryptomarket.com/terms-and-conditions/

**Pull request closed without merging**
