### PR TITLE
Batch update

### PR DESCRIPTION
**Pull request by EchterAgo**

### CODE REVIEW

**Comment by kenman345** [comment]
Btw, you can easily run the verification script locally, `rake verify`

**Comment by EchterAgo** [comment]
This should be ready to be merged now.

**Comment by EchterAgo** [comment]
Ahh, forgot an image

**Comment by EchterAgo** [comment]
Build passing now, review please

**Comment by kenman345** [comment]
hate to do this but I realized that the `country: US` thing is no good. would you mind removing those for the MS stuff and adding an exception with text like:
 "Limited to US only. Last checked may 5th, 2018"

**Comment by EchterAgo** [comment]
Sure, no problem.

**Comment by EchterAgo** [comment]
Updated

**Pull request merged**
