### PR TITLE
Batch update

### LINKED ISSUE #923: Add 'BCH Dice (Telegram Bot)' to the 'Gambling' category
Requesting to add 'BCH Dice (Telegram Bot)' to the 'Gambling' category. 

Details follow: 
```yml 
- name: BCH Dice (Telegram Bot)
      url: https://t.me/BCH_Dice_Bot
      img: 
      bch: Yes
      btc: No
      othercrypto: No
```

Resources for adding this merchant:
[Link to BCH Dice (Telegram Bot)](https://t.me/BCH_Dice_Bot)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.

### LINKED ISSUE #926: Add 'Umami Snack Import' to the 'Retailer' category
Requesting to add 'Umami Snack Import' to the 'Retailer' category. 

Details follow: 
```yml 
- name: Umami Snack Import
      url: https://www.umamisnack.ch/
      img: 
      twitter: umamisnack
      region: eu
      bch: Yes
      btc: Yes
      othercrypto: No
      doc: https://twitter.com/umamisnack/status/992325968437104641
```

Resources for adding this merchant:
Logo Provided:
Umami Snack Import

[Link to Umami Snack Import](https://www.umamisnack.ch/)
If needed, try the twitter handles profile image: [twitter.com/umamisnack](https://twitter.com/umamisnack)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.

### LINKED ISSUE #927: Add 'BitPro' to the 'Payments' category
Requesting to add 'BitPro' to the 'Payments' category. 

Details follow: 
```yml 
- name: BitPro
      url: https://bitpro.cc
      img: 
      email_address: info@bitpro.cc
      bch: Yes
      btc: Yes
      othercrypto: Yes
      doc: https://www.reddit.com/r/Bitcoincash/comments/8gqi5v/payment_gateway_bch_surpassed_btc/
```

Resources for adding this merchant:
[Link to BitPro](https://bitpro.cc)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

### PR DESCRIPTION
**Pull request by EchterAgo**
closes #923
closes #926
closes #927

### CODE REVIEW

**Comment by kenman345** [comment]
next commit can you mention the issues you're closing with `closes #[issue number goes here]` for each one so it automatically closes them?

**Comment by EchterAgo** [comment]
Ummm, I did. Or do you mean in the pull request text?

**Comment by kenman345** [comment]
may or may not be happy with you not using our repository for that to work, so you may need to mention `acceptbitcoincash/acceptbitcoincash#[number here]` for those

**Comment by kenman345** [comment]
oops
you did it on second line

**Comment by kenman345** [comment]
didnt see that first time around, sorry

**Comment by EchterAgo** [comment]
Oh, I miscapitalized CoinGate, let me update that quickly

**Comment by EchterAgo** [comment]
Fixed

**Comment by kenman345** [comment]
@EchterAgo  did we accidentally remove 6dollarshirts form the site? shouldnt it still be there but with a note about it not accepting crypto right now

**Comment by EchterAgo** [comment]
Yea, I removed it, will re-add it with the same text.

**Comment by kenman345** [comment]
and the logo....just so it doesnt error.

**Comment by EchterAgo** [comment]
What about the logo? You mean restore 6 Dollar Shirts logo? I am reverting e7fc931410bf3ef85f5b97fb175f5f00727deb63 and changing the listing.

**Comment by kenman345** [comment]
yes, reverting that commit will do the trick.

**Comment by EchterAgo** [comment]
Done

**Comment by EchterAgo** [comment]
We should have some way to attach some tags for internal usage that don't affect the search. Like a "recheck" tag.

**Comment by EchterAgo** [comment]
Oh, wrong commit message in last commit. I'll fix it.

**Comment by EchterAgo** [comment]
Should be ready now.

**Pull request merged**
